export interface InputType {
  id: string;
  text: string | number;
}

export const orgLocations: string[] = [
  "Americas",
  "APAC",
  "Asia",
  "Australia",
  "Arizona, US",
  "Atlanta, Georgia",
  "Alabama, US",
  "Austin, Texas",
  "Alberta, Canada",
  "Alexandria, Virginia",
  "Amsterdam, Netherlands",
  "Arkansas, US",
  "Antwerp, Belgium",
  "Austria",
  "Auvergne-Rhône-Alpes, France",
  "Aquitaine-Limousin-Poitou-Charentes, France",
  "Argentina",
  "Ahmedabad, India",
  "Aquitaine, France",
  "Albuquerque, New Mexico",
  "Bavaria, Germany",
  "Baden-Württemberg, Germany",
  "Belgium",
  "Berlin, Germany",
  "Bangkok, Thailand",
  "Brazil",
  "Beijing, China",
  "Bengaluru, India",
  "Boston, Massachusetts",
  "British Columbia, Canada",
  "Bogota, Colombia",
  "Brussels, Belgium",
  "Baltimore, Maryland",
  "Bremen, Germany",
  "Buffalo/Niagara, New York Area",
  "Bergen, Germany",
  "Brandenburg, Germany",
  "Birmingham, United Kingdom",
  "Baden-Baden, Germany",
  "Bucharest, Romania",
  "China",
  "Canada",
  "California, US",
  "Chicago, Illinois",
  "Czech Republic",
  "Chennai, India",
  "Colombia",
  "Charlotte, North Carolina",
  "Clamart, France",
  "Cincinnati, Ohio",
  "Columbus, Ohio",
  "Cologne, Germany",
  "Cleveland, Ohio",
  "Calgary, Canada",
  "Cape Town, South Africa",
  "Columbia, South Carolina",
  "Colorado Springs, Colorado",
  "Cambridge, Massachusetts",
  "Chengdu, China",
  "Chattanooga, Tennessee",
  "Chantilly, Virginia",
  "Dallas/Fort Worth Area",
  "Delhi, India",
  "Dallas, Texas",
  "District of Columbia, US",
  "Denver, Colorado",
  "Dublin, Ireland",
  "Dubai, United Arab Emirates",
  "Detroit, Michigan",
  "Düsseldorf, Germany",
  "Delaware, US",
  "Dresden, Germany",
  "Doha, Qatar",
  "Dayton, Ohio",
  "Durham, North Carolina",
  "Denmark",
  "Dortmund, Germany",
  "Des Moines, Iowa",
  "Dearborn, Michigan",
  "Darmstadt, Germany",
  "Deerfield Beach, Florida",
  "EMEA",
  "Europe",
  "European Union",
  "England, United Kingdom",
  "Estado de México, Mexico",
  "Edmonton, Canada",
  "Eindhoven, Netherlands",
  "Essen, Germany",
  "Englewood, Colorado",
  "Edinburgh, United Kingdom",
  "El Paso, Texas",
  "Emilia-Romagna, Italy",
  "Edison, New Jersey",
  "El Segundo, California",
  "Ernakulam, India",
  "Eden Prairie, Minnesota",
  "Evansville, Indiana",
  "Egypt",
  "Erfurt, Germany",
  "Everett, Washington",
  "France",
  "Florida, US",
  "Flanders, Belgium",
  "Frankfurt, Germany",
  "Fort Worth, Texas",
  "Fort Lauderdale, Florida",
  "Federal Territory of Kuala Lumpur, Malaysia",
  "Finland",
  "Fairfax, Virginia",
  "Fujian, China",
  "Fort Myers, Florida",
  "Fresno, California",
  "Federal Capital Territory, Nigeria",
  "Federal District, Mexico",
  "Fort Wayne, Indiana",
  "Falls Church, Virginia",
  "Fremont, California",
  "Freiburg, Germany",
  "Fargo, North Dakota",
  "Fuzhou, China",
  "Greater Houston Area",
  "Germany",
  "Greater Denver Area",
  "Greater Los Angeles Area",
  "Greater Philadelphia Area",
  "Greater New York City Area",
  "Greater Memphis Area",
  "Greater Atlanta Area",
  "Greater Milwaukee Area",
  "Greater St. Louis Area",
  "Greater Chicago Area",
  "Greater Seattle Area",
  "Greater Boston Area",
  "Georgia, US",
  "Greater Minneapolis-St. Paul Area",
  "Greater San Diego Area",
  "Greater Salt Lake City Area",
  "Greater Nashville Area",
  "Greater Omaha Area",
  "Guangdong, China",
  "Hamburg, Germany",
  "Hesse, Germany",
  "Houston, Texas",
  "Haryana, India",
  "Hong Kong",
  "Hyderabad, India",
  "Hanoi, Vietnam",
  "Hanover, Germany",
  "Hawaii, US",
  "Hangzhou, China",
  "Ho Chi Minh City, Vietnam",
  "Ho Chi Minh, Vietnam",
  "Hoograven, Netherlands",
  "Hlavní město Praha, Czech Republic",
  "Hubei, China",
  "Honolulu, Hawaii",
  "Hartford, Connecticut",
  "Herndon, Virginia",
  "Huntsville, Alabama",
  "Hungary",
  "India",
  "Illinois, US",
  "Indiana, US",
  "Iowa, US",
  "Italy",
  "Indianapolis, Indiana",
  "Ireland",
  "Israel",
  "Indonesia",
  "Idaho, US",
  "Irvine, California",
  "Indore, India",
  "Irving, Texas",
  "İstanbul, Turkey",
  "Ingolstadt, Germany",
  "Irkutsk Oblast, Russia",
  "Irkutsk, Russia",
  "Ibaraki Prefecture, Japan",
  "Ilfov County, Romania",
  "Izhevsk, Russia",
  "Japan",
  "Jerusalem, Israel",
  "Jiangsu, China",
  "Jacksonville, Florida",
  "Jalisco, Mexico",
  "Jakarta, Indonesia",
  "Johannesburg, South Africa",
  "Jersey City, New Jersey",
  "Jilin, China",
  "Jaipur, India",
  "Jackson, Mississippi",
  "Jonkoping County, Sweden",
  "Jiangxi, China",
  "Jharkhand, India",
  "Jinan, China",
  "Juriquilla, Mexico",
  "Joliet, Illinois",
  "Jeddah, Saudi Arabia",
  "Jackson, Michigan",
  "Jinhua, China",
  "Karnataka, India",
  "Kentucky, US",
  "Kansas, US",
  "Kansas City, Missouri",
  "Krasnodar Krai, Russia",
  "Kerala, India",
  "Krakow, Poland",
  "Karlsruhe, Germany",
  "Kanagawa Prefecture, Japan",
  "Knoxville, Tennessee",
  "Kuala Lumpur, Malaysia",
  "Koog aan de Zaan, Netherlands",
  "Kortrijk, Belgium",
  "Krasnodar, Russia",
  "Kazan, Russia",
  "Kansas City, Kansas",
  "Krasnoyarsk Krai, Russia",
  "Kolkata, India",
  "Kuwait",
  "Kyiv city, Ukraine",
  "Lisbon, Portugal",
  "Los Angeles, California",
  "Lower Saxony, Germany",
  "Louisiana, US",
  "Lagos, Nigeria",
  "London, United Kingdom",
  "Lima, Peru",
  "Louisville, Kentucky",
  "Lower Silesian Voivodeship, Poland",
  "Lesser Poland Voivodeship, Poland",
  "Leipzig, Germany",
  "Leeds, United Kingdom",
  "Limburg, Netherlands",
  "Lombardy, Italy",
  "Lyon, France",
  "Liaoning, China",
  "Littleton, Colorado",
  "Long Beach, California",
  "Lexington, Kentucky",
  "Leicester, United Kingdom",
  "Miami/Fort Lauderdale Area",
  "Moscow, Russia",
  "Massachusetts, US",
  "Mexico",
  "Michigan, US",
  "Maryland, US",
  "Maharashtra, India",
  "Minnesota, US",
  "Missouri, US",
  "Mumbai, India",
  "Munich, Germany",
  "Minneapolis, Minnesota",
  "Miami, Florida",
  "Moscow Oblast, Russia",
  "Masovian Voivodeship, Poland",
  "Melbourne, Australia",
  "Milwaukee, Wisconsin",
  "Mississippi, US",
  "Maine, US",
  "Manchester, United Kingdom",
  "North America",
  "New York, US",
  "Netherlands",
  "New York, New York",
  "North Rhine-Westphalia, Germany",
  "North Carolina, US",
  "New Jersey, US",
  "New Delhi, India",
  "North Holland, Netherlands",
  "New South Wales, Australia",
  "Nevada, US",
  "Nebraska, US",
  "North Brabant, Netherlands",
  "Nigeria",
  "New Hampshire, US",
  "New Mexico, US",
  "Nashville, Tennessee",
  "Nalgonda, India",
  "Nord-Pas-de-Calais, France",
  "North Dakota, US",
  "Ohio, US",
  "Ontario, Canada",
  "Oregon, US",
  "Oklahoma, US",
  "Overijssel, Netherlands",
  "Orlando, Florida",
  "Omaha, Nebraska",
  "Oklahoma City, Oklahoma",
  "Oakland, California",
  "Ottawa, Canada",
  "Osaka Prefecture, Japan",
  "Orange, California",
  "Overland Park, Kansas",
  "Osaka, Japan",
  "Oslo, Norway",
  "Olomouc Region, Czech Republic",
  "Osnabrück, Germany",
  "Omsk Oblast, Russia",
  "Omsk, Russia",
  "Oxford, United Kingdom",
  "Pennsylvania, US",
  "Poland",
  "Portugal",
  "Pune, India",
  "Phoenix, Arizona",
  "Philadelphia, Pennsylvania",
  "Pays de la Loire, France",
  "Portland, Oregon",
  "Paris, France",
  "Pittsburgh, Pennsylvania",
  "Provence-Alpes-Côte d'Azur, France",
  "Philippines",
  "Peru",
  "Porto, Portugal",
  "Porto District, Portugal",
  "Prague, Czech Republic",
  "Palo Alto, California",
  "Plano, Texas",
  "Puebla, Mexico",
  "Puerto Rico",
  "Quebec, Canada",
  "Queensland, Australia",
  "Qatar",
  "Quebec City, Canada",
  "Querétaro, Mexico",
  "Québec, Canada",
  "Qingdao, China",
  "Quincy, Massachusetts",
  "Quezon City, Philippines",
  "Quanzhou, China",
  "Quantico, Virginia",
  "Quimper, France",
  "Quincy, Illinois",
  "Queensbury, New York",
  "Quintana Roo, Mexico",
  "Quincy-sous-Sénart, France",
  "Qinghai, China",
  "Qiqiha'er, China",
  "Quincy, California",
  "Qujing, China",
  "Russia",
  "Rhineland-Palatinate, Germany",
  "Romania",
  "Rhone-Alpes, France",
  "Raleigh, North Carolina",
  "Richmond, Virginia",
  "Rhode Island, US",
  "Rotterdam, Netherlands",
  "Riyadh, Saudi Arabia",
  "Riyadh Province, Saudi Arabia",
  "Reston, Virginia",
  "Rajasthan, India",
  "Rostov Oblast, Russia",
  "Rockville, Maryland",
  "Reno, Nevada",
  "Rochester, New York",
  "Rio de Janeiro, Brazil",
  "Republic of Bashkortostan, Russia",
  "Rhône-Alpes, France",
  "Redwood City, California",
  "Shanghai, China",
  "Saint Petersburg, Russia",
  "South Carolina, US",
  "State of São Paulo, Brazil",
  "Saxony, Germany",
  "South Holland, Netherlands",
  "Stockholm County, Sweden",
  "Scotland, United Kingdom",
  "Schleswig-Holstein, Germany",
  "Saxony-Anhalt, Germany",
  "San Juan, Puerto Rico",
  "Samara Oblast, Russia",
  "Silesian Voivodeship, Poland",
  "Samut Prakan, Thailand",
  "Sverdlovsk Oblast, Russia",
  "South Dakota, US",
  "Spain",
  "State of Rio de Janeiro, Brazil",
  "Sichuan, China",
  "Shandong, China",
  "South Moravian Region, Czech Republic",
  "Texas, US",
  "Thailand",
  "Tampa/St. Petersburg, Florida Area",
  "Tennessee, US",
  "Tamil Nadu, India",
  "Telangana, India",
  "Taiwan",
  "Toronto, Canada",
  "Tampa, Florida",
  "Turkey",
  "Taipei, Taiwan",
  "Thuringia, Germany",
  "Tianjin, China",
  "Tucson, Arizona",
  "Tulsa, Oklahoma",
  "Tatarstan, Russia",
  "Tokyo, Japan",
  "Tallahassee, Florida",
  "Tempe, Arizona",
  "Troy, Michigan",
  "United States",
  "United Kingdom",
  "Utah, US",
  "Uttar Pradesh, India",
  "Utrecht, Netherlands",
  "United Arab Emirates",
  "Ukraine",
  "Ulm, Germany",
  "Ufa, Russia",
  "Uppsala County, Sweden",
  "Uusimaa, Finland",
  "Udmurt Republic, Russia",
  "Ulyanovsk Oblast, Russia",
  "Udmurtskaja Respublika, Russia",
  "Uppsala, Sweden",
  "Ulyanovsk, Russia",
  "Upper Austria, Austria",
  "Uttarakhand, India",
  "Upper Normandy, France",
  "Urbana, Illinois",
  "Virginia, US",
  "Vietnam",
  "Victoria, Australia",
  "Västra Götaland County, Sweden",
  "Vancouver, Canada",
  "Vienna, Austria",
  "Vlaanderen, Belgium",
  "Vermont, US",
  "Valle de Chalco Solidaridad, Mexico",
  "Virginia Beach, Virginia",
  "Veracruz, Mexico",
  "Voronezh Oblast, Russia",
  "Voronezh, Russia",
  "Vilvoorde, Belgium",
  "Volgograd Oblast, Russia",
  "Vancouver, Washington",
  "Versailles, France",
  "Valencian Community, Spain",
  "Vladimir Oblast, Russia",
  "Vienna, Virginia",
  "Washington D.C. Metro Area",
  "Washington, US",
  "Wisconsin, US",
  "Washington, District of Columbia",
  "Wetering, Netherlands",
  "West Virginia, US",
  "Warsaw, Poland",
  "Western Cape, South Africa",
  "Wrocław, Poland",
  "Wales, United Kingdom",
  "Wyoming, US",
  "Western Australia, Australia",
  "Wuhan, China",
  "Walloon Region, Belgium",
  "Wichita, Kansas",
  "Whitby, Canada",
  "Winnipeg, Canada",
  "Worcester, Massachusetts",
  "West Palm Beach, Florida",
  "West Bengal, India",
  "Xi'an, China",
  "Xenia, Ohio",
  "Xuzhou, China",
  "Xining, China",
  "Xiaogan, China",
  "Xingtai, China",
  "Xizang (Tibet), China",
  "Xinjiang, China",
  "Xiamen, China",
  "Xanten, Germany",
  "Xanxerê, Brazil",
  "Xambioá, Brazil",
  "Xinjiang Weiwuerzizhiqu, China",
  "Xicoténcatl, Mexico",
  "Xilxes, Spain",
  "Xenia, Illinois",
  "Xalapa, Mexico",
  "Xochihuehuetlán, Mexico",
  "Xàtiva, Spain",
  "Xirivella, Spain",
  "Yekaterinburg, Russia",
  "York, Pennsylvania",
  "Yokohama, Japan",
  "Yaroslavl Oblast, Russia",
  "Yaroslavl, Russia",
  "Youngstown, Ohio",
  "Yucatán, Mexico",
  "Ypenburg, Netherlands",
  "Ypres, Belgium",
  "Yonkers, New York",
  "Yuma, Arizona",
  "Yamalo-Nenets Autonomous Okrug, Russia",
  "Yucaipa, California",
  "Yamaguchi Prefecture, Japan",
  "Yakima, Washington",
  "Yantai, China",
  "Yunnan, China",
  "Ypsilanti, Michigan",
  "York, United Kingdom",
  "Yoshkar-Ola, Russia",
  "Zhejiang, China",
  "Zurich, Switzerland",
  "Zürich, Switzerland", // Note: "Zurich" and "Zürich" are the same location, with different spellings.
  "Zuid-Holland, Netherlands",
  "Zapopan, Mexico",
  "Zeeland, Netherlands",
  "Zwolle, Netherlands",
  "Zhuhai, China",
  "Zlin Region, Czech Republic",
  "Zelenograd, Russia",
  "Zaventem, Belgium",
  "Zaandam, Netherlands",
  "Zwickau, Germany",
  "Zaragoza, Spain",
  "Zionsville, Indiana",
  "Zabaykalsky Krai, Russia",
  "Zanesville, Ohio",
  "Zielona Gora, Poland",
  "Zunyi, China",
  "Zephyrhills, Florida",
];

export const jobTitles: string[] = [
  "account manager",
  "associate",
  "administrative assistant",
  "accountant",
  "account executive",
  "assistant manager",
  "analyst",
  "assistant professor",
  "associate professor",
  "administrator",

  "attorney",
  "agent",
  "area manager",
  "administrativo",
  "architect",
  "admin",
  "auditor",
  "assistant",
  "analista",
  "associate director",
  "business analyst",
  "business development manager",
  "branch manager",
  "business manager",
  "buyer",
  "business development",
  "broker",
  "banker",
  "business development executive",
  "business consultant",
  "brand manager",
  "bookkeeper",
  "barista",
  "broker associate",
  "bartender",
  "board member",
  "business development director",
  "business",
  "business owner",
  "boss",
  "consultant",
  "ceo",
  "customer service",
  "controller",
  "customer service representative",
  "cashier",
  "cfo",
  "csr",
  "clerk",
  "civil engineer",
  "coordinator",
  "creative director",
  "customer service manager",
  "chef",
  "co-founder",
  "chief operating officer",
  "customer support supervisor",
  "customer support officer",
  "consultor",
  "chief financial officer",
  "case manager",
  "captain",
  "director",
  "docente",
  "designer",
  "developer",
  "design engineer",
  "driver",
  "district manager",
  "director of operations",
  "doctor",
  "deputy manager",
  "directeur",
  "director of sales",
  "data analyst",
  "dr",
  "district sales manager",
  "director of marketing",
  "diretor",
  "director of business development",
  "development manager",
  "department manager",
  "engineer",
  "executive assistant",
  "executive director",
  "executive",
  "electrical engineer",
  "educator",
  "empleado",
  "editor",
  "engineering manager",
  "electrician",
  "estudiante",
  "employee",
  "estudante",
  "english teacher",
  "enseignante",
  "enseignant",
  "empleada",
  "executive vice president",
  "economist",
  "executive secretary",
  "financial analyst",
  "financial advisor",
  "finance manager",
  "founder",
  "financial controller",
  "flight attendant",
  "finance",
  "founder and ceo",
  "field engineer",
  "finance director",
  "field service engineer",
  "faculty",
  "financial consultant",
  "facilities manager",
  "funzionario",
  "financial manager",
  "financial representative",
  "foreman",
  "financial planner",
  "facility manager",
  "general manager",
  "gerente",
  "graphic designer",
  "graduate student",
  "graduate research assistant",
  "gerente comercial",
  "gm",
  "graduate assistant",
  "graduate teaching assistant",
  "geologist",
  "gerente general",
  "group leader",
  "general counsel",
  "geschäftsführer",
  "gepensioneerd",
  "geometra",
  "gerente de projetos",
  "group manager",
  "graphic artist",
  "gerente de vendas",
  "hr manager",
  "hr",
  "human resources manager",
  "human resources",
  "hr business partner",
  "hr executive",
  "hr specialist",
  "hr generalist",
  "hr assistant",
  "hr officer",
  "hr consultant",
  "hr coordinator",
  "hr director",
  "human resources generalist",
  "hr advisor",
  "hr administrator",
  "human resources specialist",
  "housewife",
  "homemaker",
  "human resource manager",
  "intern",
  "instructor",
  "it manager",
  "impiegato",
  "it",
  "impiegata",
  "it specialist",
  "it consultant",
  "insurance agent",
  "independent consultant",
  "it analyst",
  "inside sales",
  "internal auditor",
  "it project manager",
  "inspector",
  "internship",
  "independent distributor",
  "interior designer",
  "insegnante",
  "inside sales representative",
  "journalist",
  "java developer",
  "jubilado",
  "jefe",
  "junior consultant",
  "journaliste",
  "junior engineer",
  "jubilada",
  "juriste",
  "jefe de proyectos",
  "jefe de proyecto",
  "jefe de departamento",
  "jornalista",
  "junior accountant",
  "jefe de ventas",
  "jurist",
  "junior software engineer",
  "junior designer",
  "junior software developer",
  "junior associate",
  "key account manager",
  "kindergarten teacher",
  "konsulent",
  "kam",
  "key account executive",
  "key accounts manager",
  "konsult",
  "kitchen manager",
  "key account",
  "key holder",
  "karyawan",
  "kunderådgiver",
  "kitchen designer",
  "koordinator",
  "kontorassistent",
  "kierownik",
  "kundekonsulent",
  "keyholder",
  "key account specialist",
  "knowledge manager",
  "lecturer",
  "legal assistant",
  "lawyer",
  "legal secretary",
  "librarian",
  "lpn",
  "logistics manager",
  "loan officer",
  "lead engineer",
  "legal counsel",
  "logistics",
  "logistics coordinator",
  "laboratory technician",
  "letter carrier",
  "law clerk",
  "lab technician",
  "lead consultant",
  "libero professionista",
  "lead software engineer",
  "library assistant",
  "manager",
  "managing director",
  "marketing manager",
  "marketing",
  "mechanical engineer",
  "managing partner",
  "marketing coordinator",
  "md",
  "marketing director",
  "mr",
  "marketing executive",
  "medico",
  "marketing assistant",
  "management trainee",
  "merchandiser",
  "manufacturing engineer",
  "marketing specialist",
  "mechanic",
  "medical assistant",
  "maintenance manager",
  "nurse",
  "network engineer",
  "network administrator",
  "none",
  "national account manager",
  "national sales manager",
  "nurse practitioner",
  "n a",
  "ninguno",
  "na",
  "nurse manager",
  "no",
  "nursing",
  "nutricionista",
  "nanny",
  "network analyst",
  "nil",
  "network technician",
  "network manager",
  "network specialist",
  "owner",
  "operations manager",
  "office manager",
  "officer",
  "operator",
  "office administrator",
  "office assistant",
  "operations",
  "occupational therapist",
  "operations supervisor",
  "operations director",
  "operation manager",
  "operaio",
  "operador",
  "operations analyst",
  "operations coordinator",
  "office coordinator",
  "owner operator",
  "operations specialist",
  "outside sales",
  "project manager",
  "professor",
  "partner",
  "president",
  "project engineer",
  "product manager",
  "principal",
  "program manager",
  "professora",
  "phd student",
  "project coordinator",
  "production manager",
  "pharmacist",
  "paralegal",
  "process engineer",
  "profesor",
  "programmer",
  "physician",
  "pilot",
  "programmer analyst",
  "quality manager",
  "quality engineer",
  "qa engineer",
  "qa",
  "quality assurance",
  "quantity surveyor",
  "quality analyst",
  "quality assurance manager",
  "quadro",
  "qa manager",
  "qa analyst",
  "quality control",
  "quality assurance analyst",
  "quality assurance engineer",
  "quality assurance specialist",
  "quadro direttivo",
  "qa lead",
  "qc",
  "quality inspector",
  "quality",
  "realtor",
  "rn",
  "registered nurse",
  "research assistant",
  "receptionist",
  "researcher",
  "regional sales manager",
  "recruiter",
  "research associate",
  "real estate agent",
  "regional manager",
  "relationship manager",
  "recruitment consultant",
  "research scientist",
  "retraité",
  "research analyst",
  "research fellow",
  "real estate broker",
  "reporter",
  "regional director",
  "student",
  "software engineer",
  "sales manager",
  "sales",
  "supervisor",
  "software developer",
  "senior consultant",
  "sales associate",
  "senior software engineer",
  "sales representative",
  "store manager",
  "senior manager",
  "secretary",
  "senior project manager",
  "sales executive",
  "senior associate",
  "senior engineer",
  "system engineer",
  "systems engineer",
  "sales consultant",
  "teacher",
  "team leader",
  "technician",
  "territory manager",
  "team lead",
  "teaching assistant",
  "trainee",
  "tecnico",
  "technical manager",
  "technical lead",
  "test engineer",
  "trainer",
  "technical consultant",
  "teller",
  "team manager",
  "technical support",
  "tutor",
  "technical director",
  "tech",
  "technical support engineer",
  "underwriter",
  "unemployed",
  "unit manager",
  "undergraduate research assistant",
  "ux designer",
  "uzman",
  "unternehmensinhaber",
  "user experience designer",
  "undergraduate student",
  "undergraduate researcher",
  "unit secretary",
  "university lecturer",
  "ui designer",
  "underwriting assistant",
  "uitvoerder",
  "undergraduate",
  "undersköterska",
  "ui developer",
  "ui ux designer",
  "university professor",
  "vice president",
  "vp",
  "vendedor",
  "volunteer",
  "vendedora",
  "ventas",
  "verpleegkundige",
  "visual merchandiser",
  "vice president of operations",
  "vice president of sales",
  "vp sales",
  "vp operations",
  "vp business development",
  "vigilante",
  "vendas",
  "vice president business development",
  "vice president sales",
  "video editor",
  "vice president operations",
  "vice president human resources",
  "web developer",
  "web designer",
  "warehouse manager",
  "writer",
  "waitress",
  "worker",
  "warehouse supervisor",
  "welder",
  "webmaster",
  "waiter",
  "warehouse",
  "wissenschaftlicher mitarbeiter",
  "werkvoorbereider",
  "warehouse worker",
  "warehouse associate",
  "web application developer",
  "wealth manager",
  "work",
  "wissenschaftliche mitarbeiterin",
  "webdesigner",
  "xray tech",
  "x-ray tech",
  "x-ray technologist",
  "xray technologist",
  "yönetici",
  "yoga instructor",
  "youth worker",
  "yoga teacher",
  "yönetmen",
  "yok",
  "yes",
  "youth pastor",
  "yönetici asistanı",
  "yazılım uzmanı",
  "yetkili",
  "yrd. doç. dr.",
  "youth counselor",
  "y",
  "yrd.doç.dr.",
  "yÖnetİcİ",
  "youth director",
  "youth care worker",
  "youth minister",
  "yacht broker",
  "zaakvoerder",
  "zone manager",
  "zonal manager",
  "zonal sales manager",
  "zumba instructor",
  "zonal business manager",
  "zonal head",
  "zorgcoördinator",
  "zorgcoordinator",
  "zorgkundige",
  "z",
  "zootecnista",
  "zelfstandig ondernemer",
  "zsm",
  "zorgmanager",
  "zone merchandise supervisor",
  "zelfstandig",
  "zelfstandige",
  "ziekenverzorgende",
  "zumba fitness instructor",
];
export const seniorities: string[] = [
  "owner",
  "founder",
  "c_suite",
  "partner",
  "vp",
  "head",
  "director",
  "manager",
  "senior",
  "entry",
  "intern",
];

export const emailStatusOptions: string[] = [
  "Verified",
  "Guessed",
  "Unavailable",
  "Bounced",
  "Pending Manual Fulfillment",
];

export const keywords = [
  { name: "accounting", value: "5567ce1f7369643b78570000" },
  { name: "agriculture", value: "55718f947369642142b84a12" },
  { name: "airlines/aviation", value: "5567e0bf7369641d115f0200" },
  {
    name: "alternative dispute resolution",
    value: "5567e1a87369641f6d550100",
  },
  { name: "alternative medicine", value: "5567e27c7369642ade490000" },
  { name: "animation", value: "5567e36f73696431a4970000" },
  { name: "apparel & fashion", value: "5567cd82736964540d0b0000" },
  { name: "architecture & planning", value: "5567cdb77369645401080000" },
  { name: "arts & crafts", value: "5567cd4d73696439d9030000" },
  { name: "automotive", value: "5567cdf27369644cfd800000" },
  { name: "aviation & aerospace", value: "5567e0dd73696416d3c20100" },
  { name: "banking", value: "5567ce237369644ee5490000" },
  { name: "biotechnology", value: "5567d08e7369645dbc4b0000" },
  { name: "broadcast media", value: "5567e0f973696416d34e0200" },
  { name: "building materials", value: "5567e1a17369641ea9d30100" },
  {
    name: "business supplies & equipment",
    value: "5567e0fa73696410e4c51200",
  },
  { name: "capital markets", value: "5567cdb773696439a9080000" },
  { name: "chemicals", value: "5567e21e73696426a1030000" },
  { name: "civic & social organization", value: "5567cdda7369644eed130000" },
  { name: "civil engineering", value: "5567e13a73696418756e0200" },
  { name: "commercial real estate", value: "5567e1887369641d68d40100" },
  { name: "computer & network security", value: "5567cd877369644cf94b0000" },
  { name: "computer games", value: "5567cd8b736964540d0f0000" },
  { name: "computer hardware", value: "5567e0d47369641233eb0600" },
  { name: "computer networking", value: "5567cdbe7369643b78360000" },
  { name: "computer software", value: "5567cd4e7369643b70010000" },
  { name: "construction", value: "5567cd4773696439dd350000" },
  { name: "consumer electronics", value: "consumer electronics" },
  { name: "consumer goods", value: "5567e1947369641ead570000" },
  { name: "consumer services", value: "5567d1127261697f2b1d0000" },
  { name: "cosmetics", value: "5567e1ae73696423dc040000" },
  { name: "dairy", value: "5567e8a27369646ddb0b0000" },
  { name: "defense & space", value: "5567e1097369641b5f810500" },
  { name: "design", value: "5567cdbc73696439d90b0000" },
  { name: "e-learning", value: "5567e19c7369641c48e70100" },
  { name: "education management", value: "5567ce9e736964540d540000" },
  {
    name: "electrical/electronic manufacturing",
    value: "5567cd4c73696439c9030000",
  },
  { name: "entertainment", value: "5567cdd37369643b80510000" },
  { name: "environmental services", value: "5567ce5b736964540d280000" },
  { name: "events services", value: "5567cd8e7369645409450000" },
  { name: "executive office", value: "5567e09473696410dbf00700" },
  { name: "facilities services", value: "5567ce9c7369643bc9980000" },
  { name: "farming", value: "5567cd4f7369644d2d010000" },
  { name: "financial services", value: "5567cdd67369643e64020000" },
  { name: "fine art", value: "5567e2097369642420150000" },
  { name: "fishery", value: "5567f96c7369642a22080000" },
  { name: "food & beverages", value: "5567ce1e7369643b806a0000" },
  { name: "food production", value: "5567e1b3736964208b280000" },
  { name: "fund-raising", value: "5567d2ad7261697f2b1f0100" },
  { name: "furniture", value: "5567cede73696440d0040000" },
  { name: "gambling & casinos", value: "5567e0cf7369641233e50600" },
  { name: "glass, ceramics & concrete", value: "5567cd4f736964397e030000" },
  { name: "government administration", value: "5567cd527369643981050000" },
  { name: "government relations", value: "5567e29b736964256c370100" },
  { name: "graphic design", value: "5567cd4d73696439d9040000" },
  { name: "health, wellness & fitness", value: "5567cddb7369644d250c0000" },
  { name: "higher education", value: "5567cd4c73696453e1300000" },
  { name: "hospital & health care", value: "5567cdde73696439812c0000" },
  { name: "hospitality", value: "5567ce9d7369643bc19c0000" },
  { name: "human resources", value: "5567e0e37369640e5ac10c00" },
  { name: "import & export", value: "5567ce9d7369645430c50000" },
  {
    name: "individual & family services",
    value: "5567d02b7369645d8b140000",
  },
  { name: "industrial automation", value: "5567e1337369641ad2970000" },
  { name: "information services", value: "5567e0c97369640d2b3b1600" },
  {
    name: "information technology & services",
    value: "5567cd4773696439b10b0000",
  },
  { name: "insurance", value: "5567cdd973696453d93f0000" },
  { name: "international affairs", value: "5567e3657369642f4ec90000" },
  {
    name: "international trade & development",
    value: "5567ce9c7369644eed680000",
  },
  { name: "internet", value: "5567cd4d736964397e020000" },
  { name: "investment banking", value: "5567e1ab7369641f6d660100" },
  { name: "investment management", value: "5567e0bc7369641d11550200" },
  { name: "judiciary", value: "55680a8273696407b61f0000" },
  { name: "law enforcement", value: "5567e0e073696408da441e00" },
  { name: "law practice", value: "5567ce1f7369644d391c0000" },
  { name: "legal services", value: "5567ce2d7369644d25250000" },
  { name: "legislative office", value: "5567e1797369641c48c10100" },
  { name: "leisure, travel & tourism", value: "5567cdd87369643bc12f0000" },
  { name: "libraries", value: "556808697369647bfd420000" },
  { name: "logistics & supply chain", value: "5567cd4973696439b9010000" },
  { name: "luxury goods & jewelry", value: "5567cda97369644cfd3e0000" },
  { name: "machinery", value: "5567cd4973696439d53c0000" },
  { name: "management consulting", value: "5567cdd47369643dbf260000" },
  { name: "maritime", value: "5567cd8273696439b1240000" },
  { name: "market research", value: "5567e1387369641ec75d0200" },
  { name: "marketing & advertising", value: "5567cd467369644d39040000" },
  {
    name: "mechanical or industrial engineering",
    value: "5567ce2673696453d95c0000",
  },
  { name: "media production", value: "5567e0ea7369640d2ba31600" },
  { name: "medical devices", value: "5567e1b97369641ea9690200" },
  { name: "medical practice", value: "5567d0467369645dbc200000" },
  { name: "mental health care", value: "5567ce2773696454308f0000" },
  { name: "military", value: "5567e2c572616932bb3b0000" },
  { name: "mining & metals", value: "5567e3f3736964395d7a0000" },
  { name: "motion pictures & film", value: "5567cdd7736964540d130000" },
  { name: "museums & institutions", value: "5567e15373696422aa0a0000" },
  { name: "music", value: "5567cd4f736964540d050000" },
  { name: "nanotechnology", value: "5567e7be736964110e210000" },
  { name: "newspapers", value: "5567cd4a73696439a9010000" },
  {
    name: "nonprofit organization management",
    value: "5567cd4773696454303a0000",
  },
  { name: "oil & energy", value: "5567cdd97369645624020000" },
  { name: "online media", value: "5567cdb373696439dd540000" },
  { name: "outsourcing/offshoring", value: "5567d04173696457ee520000" },
  { name: "package/freight delivery", value: "5567e8bb7369641a658f0000" },
  { name: "packaging & containers", value: "5567e36973696431a4480000" },
  { name: "paper & forest products", value: "5567e97f7369641e57730100" },
  { name: "performing arts", value: "5567e0af7369641ec7300000" },
  { name: "pharmaceuticals", value: "5567e0eb73696410e4bd1200" },
  { name: "philanthropy", value: "5567ce9673696453d99f0000" },
  { name: "photography", value: "5567cd4f7369644cfd250000" },
  { name: "plastics", value: "5567cdda7369644cf95d0000" },
  { name: "political organization", value: "5567e25f736964256cff0000" },
  { name: "primary/secondary education", value: "5567cdd97369645430680000" },
  { name: "printing", value: "5567cd4d7369644d513e0000" },
  {
    name: "professional training & coaching",
    value: "5567cd49736964541d010000",
  },
  { name: "program development", value: "5567e2907369642433e60200" },
  { name: "public policy", value: "5567e28a7369642ae2500000" },
  {
    name: "public relations & communications",
    value: "5567ce5973696453d9780000",
  },
  { name: "public safety", value: "5567cd4a7369643ba9010000" },
  { name: "publishing", value: "5567ce5b73696439a17a0000" },
  { name: "railroad manufacture", value: "5567e14673696416d38c0300" },
  { name: "ranching", value: "5567fd5a73696442b0f20000" },
  { name: "real estate", value: "5567cd477369645401010000" },
  {
    name: "recreational facilities & services",
    value: "5567e134736964214f5e0000",
  },
  { name: "religious institutions", value: "5567e0f27369640e5aed0c00" },
  { name: "renewables & environment", value: "5567cd49736964540d020000" },
  { name: "research", value: "5567e09f736964160ebb0100" },
  { name: "restaurants", value: "5567e0e0736964198de70700" },
  { name: "retail", value: "5567ced173696450cb580000" },
  { name: "security & investigations", value: "5567e19b7369641ead740000" },
  { name: "semiconductors", value: "5567e0d87369640e5aa30c00" },
  { name: "shipbuilding", value: "5568047d7369646d406c0000" },
  { name: "sporting goods", value: "5567e113736964198d5e0800" },
  { name: "sports", value: "5567ce227369644eed290000" },
  { name: "staffing & recruiting", value: "5567e09973696410db020800" },
  { name: "supermarkets", value: "5567e2a97369642a553d0000" },
  { name: "telecommunications", value: "5567cd4c7369644d39080000" },
  { name: "textiles", value: "5567e1327369641d91ce0300" },
  { name: "think tanks", value: "5567e1de7369642069ea0100" },
  { name: "tobacco", value: "55680085736964551e070000" },
  { name: "translation & localization", value: "5567e1097369641d91230300" },
  {
    name: "transportation/trucking/railroad",
    value: "5567cd4e7369644cf93b0000",
  },
  { name: "utilities", value: "5567e2127369642420170000" },
  {
    name: "venture capital & private equity",
    value: "5567e1587369641c48370000",
  },
  { name: "veterinary", value: "5567ce9673696439d5c10000" },
  { name: "warehousing", value: "5567e127736964181e700200" },
  { name: "wholesale", value: "5567d01e73696457ee100000" },
  { name: "wine & spirits", value: "5567cd4d7369643b78100000" },
  { name: "wireless", value: "5567e3ca736964371b130000" },
  { name: "writing & editing", value: "5567cdd973696439a1370000" },
];


export const companyDomains = [
  { companyName: "Walmart", organizationId: "5f8e6117ab820101120cc9ff" },
  { companyName: "Amazon", organizationId: "5f2a39cb77a7440112460cf5" },
  { companyName: "Apple", organizationId: "5fcd2cf3ed78c700f9383e4e" },
  { companyName: "CVS Health", organizationId: "5e62d73eb0c04e008ccbe82f" },
  { companyName: "UnitedHealth Group", organizationId: "5e58534210d2250001e13da1" },
  { companyName: "Berkshire Hathaway", organizationId: "6181a79eec541e008c0bd8ac" },
  { companyName: "ExxonMobil", organizationId: "5d0a137080f93ecc1c79edf8" },
  { companyName: "Alphabet", organizationId: "57c4a824a6da98411e7df3eb" },
  { companyName: "McKesson", organizationId: "5b262253a3ae61f442a98c26" },
  { companyName: "AmerisourceBergen", organizationId: "54a134ec69702d4494465400" },
  { companyName: "Cigna", organizationId: "63ea37cad658bf00a3766172" },
  { companyName: "AT&T", organizationId: "5a9d953ca6da98d9663f8089" },
  { companyName: "Costco Wholesale", organizationId: "54a11ca569702d84c591b500" },
  { companyName: "Cardinal Health", organizationId: "55921466736964186a2e5800" },
  { companyName: "Microsoft", organizationId: "62337760d02af100a5ca2468" },
  { companyName: "Walgreens Boots Alliance", organizationId: "559225587369641b33075900" },
  { companyName: "Home Depot", organizationId: "5fc98029fc2f9600019df305" },
  { companyName: "Marathon Petroleum", organizationId: "54a11bb069702d86b6245000" },
  { companyName: "Chevron", organizationId: "5f49df5c1fe0980001b3b364" },
  { companyName: "Verizon", organizationId: "5f4068ae2c39f70001b8b6fb" },
  { companyName: "Ford Motor", organizationId: "55e1552ff3e5bb2fe0000003" },
  { companyName: "General Motors", organizationId: "5f5fa368134e120100e8fe6b" },
  { companyName: "Anthem", organizationId: "5500b6de7369641734430200" },
  { companyName: "Kroger", organizationId: "54a1356a69702d3cbb35b900" },
  { companyName: "JPMorgan Chase", organizationId: "61f934b9cff53400dbb76c6e" },
  { companyName: "Bank of America", organizationId: "54a12ae269702db648e84202" },
  { companyName: "Wells Fargo", organizationId: "5d09a098a3ae61763b04abbf" },
  { companyName: "Citigroup", organizationId: "5592234f7369641739ce2f00" },
  { companyName: "Freddie Mac", organizationId: "54a1396b69702d231f827300" },
  { companyName: "Fannie Mae", organizationId: "54a13bc369702dc8e43d8c01" },
  { companyName: "IBM", organizationId: "5d33d0d1a3ae6113e19b1674" },
  { companyName: "Tesla", organizationId: "57c4d9dea6da9869f38f20af" },
  { companyName: "Meta (Facebook)", organizationId: "5f48e4944c270e0001e2bb7f" },
  { companyName: "Procter & Gamble", organizationId: "54a1218a69702d94a403bf02" },
  { companyName: "PepsiCo", organizationId: "6255dd218537e400a53888b3" },
  { companyName: "Comcast", organizationId: "5f5c8daa73412a00e27370fc" },
  { companyName: "Pfizer", organizationId: "54a11e6069702d94a4944501" },
  { companyName: "Johnson & Johnson", organizationId: "61758b94c9e96e008cb9b1dd" },
  { companyName: "Caterpillar", organizationId: "5e699a8d1d525e00980b32e4" },
  { companyName: "FedEx", organizationId: "55921d4e7369643bdd271c00" },
  { companyName: "Goldman Sachs", organizationId: "5da2e6a3f978a8000177e831" },
  { companyName: "Morgan Stanley", organizationId: "66efde9ddb74ef0001c7011f" },
  { companyName: "Intel", organizationId: "5f55c37c2a079e00ffd677ec" },
  { companyName: "Lockheed Martin", organizationId: "5fcb9468fe44810001e97eba" },
  { companyName: "Merck", organizationId: "6048540916abe500012201fe" },
  { companyName: "Target", organizationId: "5f4b5d08368cd60001abdeaf" },
  { companyName: "Lowe's", organizationId: "619dca1525825d008ca4668c" },
  { companyName: "Boeing", organizationId: "54a1229169702d9a8b695403" },
  { companyName: "American Airlines", organizationId: "5da65de01eafc200013d00e0" },
  { companyName: "HCA Healthcare", organizationId: "5d0a8682f651252325f2a375" },
  { companyName: "USAA", organizationId: "54a11ef969702d8ccc28b401" },
  { companyName: "T-Mobile", organizationId: "5d09381da3ae61b7f7b73360" },
  { companyName: "Qualcomm", organizationId: "5f6316994abf0b008ce52a3f" },
  { companyName: "3M", organizationId: "5edba935e36c200001d51dcb" },
  { companyName: "Google", organizationId: "5fc93db64c38d300d6aa24e6" },
  { companyName: "Google DeepMind", organizationId: "57c4b74da6da98370bc9529f" },
  { companyName: "Google AdSense", organizationId: "55922fea7369641908c1ba00" },
  { companyName: "Fitbit (now part of Google)", organizationId: "5f48e0d76ea2bf0001aa0aff" },
  { companyName: "Amazon Web Services (AWS)", organizationId: "5f2987132c142600daf44da0" },
  { companyName: "Amazon Lab126", organizationId: "5c22f9eaa3ae61e966f1fe79" },
  { companyName: "Prime Video & Amazon MGM Studios", organizationId: "5f47efc3844fa30001f8644c" },
  { companyName: "Amazon Games", organizationId: "61ec25d3428bc900012f4475" },
  { companyName: "Amazon Logistics", organizationId: "5b83dc01324d44116dde1ca3" },
  { companyName: "Amazon Fulfillment Technologies & Robotics", organizationId: "55ec9936f3e5bb12e8003cc5" },
  { companyName: "Samsung", organizationId:"6279918b8850d6008dc3a5d2"},
  { companyName: "MetLife", organizationId:"6241849c64051c00a550fda4"},
  { companyName: "Progressive", organizationId:"54a1d0f774686949e7fb7513"},
  { companyName: "Deere", organizationId:"615dc78121eb73000160beee"},
  { companyName: "Nvidia", organizationId:"5f50a22da4560d00e3eddf31"},
  { companyName: "StoneX Group", organizationId:"66056950b4f1d90300678ada"},
  { companyName: "ConocoPhillips", organizationId:"54a1277169702d8b195af300"},
  { companyName: "Delta Air Lines", organizationId:"55923f95736964189389f100"},
  { companyName: "TD Synnex", organizationId:"54a13acf69702d2bfd402b01"},
  { companyName: "Publix Super Markets", organizationId:"5dad5eb14ff61d0001175441"},
  { companyName: "Allstate", organizationId:"5da62af074723100dabd45ab"},
  { companyName: "Cisco", organizationId:"62987dc94fbae900a51766b3"},
  { companyName: "Nationwide", organizationId:"5f4146ac9511730001d207b3"},
  { companyName: "Charter Communications", organizationId:"5d09ba79f651253df07e01ea"},
  { companyName: "AbbVie", organizationId:"5fc7b2ff4045230110edd2a1"},
  { companyName: "New York Life Insurance", organizationId:"5a9e9088a6da98d9356cf338"},
  { companyName: "TJX", organizationId:"54a1289d69702d9313d02d01"},
  { companyName: "Prudential Financial", organizationId:"54a1a3857468694f8f9beb03"},
  { companyName: "HP", organizationId:"57c53a82a6da984be99ba3b4"},
  { companyName: "Performance Food Group", organizationId:"54a23af67468692e71cb4218"},
  { companyName: "Tyson Foods", organizationId:"5e6fa9c37c894100fdb7059b"},
  { companyName: "Liberty Mutual Insurance", organizationId:"5fc99764e93ce60001857006"},
  { companyName: "Nike", organizationId:"5f497ca3b2162b0001bbfd46"},
  { companyName: "Oracle", organizationId:"5f435719789e1300becc23b0"},
  { companyName: "Enterprise Products Partners", organizationId:"636848108cc43f000178a82b"},
  { companyName: "Capital One Financial", organizationId:"65c23586fa2544030087522c"},
  { companyName: "Plains GP Holdings", organizationId:"57c4db0da6da986a6f8d20d1"},
  { companyName: "World Kinect", organizationId:"5d0a228aa3ae61afb98854e6"},
  { companyName: "American International Group", organizationId:"5e58328c9303fe00012876ba"},
  { companyName: "Coca-Cola", organizationId:"56e32e01f3e5bb2e9b008cf0"},
  { companyName: "TIAA", organizationId:"59bbab20a6da98e6e7ee39b6"},
  { companyName: "CHS", organizationId:"5a9f6ce9a6da98d9a15f0c86"},
  { companyName: "Bristol-Myers Squibb", organizationId:"54a1b144746869401234aa08"},
  { companyName: "Dow", organizationId:"54a11e3769702d97c10e6a01"},
  { companyName: "Best Buy", organizationId:"54a12a2669702d93135c0902"},
  { companyName: "Thermo Fisher Scientific", organizationId:"5b12e7e6a6da98dcb5c6791b"},
  { companyName: "Massachusetts Mutual Life Insurance", organizationId:"5edbac5ab0febc00016c9fd4"},
  { companyName: "General Dynamics", organizationId:"5f49b1a4a845d3000189667b"},
  { companyName: "Travelers", organizationId:"54a11c9b69702da42583b500"},
  { companyName: "Warner Bros. Discovery", organizationId:"612ba6b0f8c74d0001bdcb4d"},
  { companyName: "U.S. Bancorp", organizationId:"55f25bb0f3e5bb0b73003d91"},
  { companyName: "abbott", organizationId:"5d09d9c0a3ae61974d1aacc6"},
  { companyName: "Northrop Grumman", organizationId:"60999a9944cb3700c91a84d8"},
  { companyName: "Northwestern Mutual", organizationId:"54a1276269702d90a2c3b400"},
  { companyName: "Dollar General", organizationId:"54a11be369702d84c5506300"},
  { companyName: "PBF Energy", organizationId:"54a19ec174686942d31e7b02"},
  { companyName: "Uber", organizationId:"5e57b09b0f85860001915922"},
  { companyName: "Honeywell", organizationId:"54a1285569702d8cfcfa3b01"},
  { companyName: "Starbucks", organizationId:"5d88848ad64d780098cb9eef"},
  { companyName: "Broadcom", organizationId:"5e5839087c5fe400010a955c"},
  { companyName: "US Foods", organizationId:"5ed101a1e3781e000147f36a"},
  { companyName: "D.R. Horton", organizationId:"54a1297169702d8eeb31ea01"},
  { companyName: "Philip Morris International", organizationId:"5f44e44ff0e10700016835e8"},
  { companyName: "Paccar", organizationId:"54a127e069702da2207ac700"},
  { companyName: "Salesforce", organizationId:"5a9f506ea6da98d99781eff8"},
  { companyName: "Nucor", organizationId:"54a1a4347468694012c71704"},
  { companyName: "Jabil", organizationId:"5da144e56a35ec00013f9e04"},
  { companyName: "Lennar", organizationId:"54a11b1869702da753821500"},
  { companyName: "Eli Lilly", organizationId:"54a11fef69702d8ed45b0b02"},
  { companyName: "Molina Healthcare", organizationId:"54a1342f69702d2db4406a00"},
  { companyName: "Cummins", organizationId:"601a98723a044600cce76294"},
  { companyName: "Bank of New York Mellon", organizationId:"5da3df353a4e680001cabf20"},
  { companyName: "Netflix", organizationId:"54a1998674686949e7a2b400"},
  { companyName: "Truist Financial", organizationId:"5fd1aae69c752d0001054ff2"},
  { companyName: "Arrow Electronics", organizationId:"54a23ca47468693a7ea19518"},
  { companyName: "Visa", organizationId:"55e15fadf3e5bb3446000099"},
  { companyName: "Apollo Global Management", organizationId:"55920eb273696418b72a4100"},
  { companyName: "HF Sinclair", organizationId:"6397e3e3fec8e600a41ee10c"},
  { companyName: "CBRE", organizationId:"57c4ef44a6da986ac7437a9c"},
  { companyName: "PNC Financial Services", organizationId:"54a1209a69702da753c65002"},
  { companyName: "Lithia", organizationId:"66e400d1980b660e18fac59a"},
  { companyName: "CarMax", organizationId:"54a126d369702dab37a10300"},
  { companyName: "Paramount Global", organizationId:"54a1291169702d8b19cce901"},
  { companyName: "Dollar Tree", organizationId:"62a0490f559f2900b2dea6ed"},
  { companyName: "United Natural Foods", organizationId:"615d38efe1fd780001514bf1"},
  { companyName: "PayPal Holdings", organizationId:"55923de0736964186f02ef00"},
  { companyName: "Penske Automotive Group", organizationId:"57c4a544a6da982bb6fbd01f"},
  { companyName: "Hewlett Packard Enterprise", organizationId:"56dd0d18f3e5bb1ac9000fea"},
  { companyName: "Duke Energy", organizationId:"54a11c9b69702d8ccccdb400"},
  { companyName: "Occidental Petroleum", organizationId:"54a1364969702d36c99b1501"},
  { companyName: "NRG Energy", organizationId:"5500b52f7369647a8fb40e00"},
  { companyName: "Amgen", organizationId:"54a122ad69702d9a8b3d6003"},
  { companyName: "NextEra Energy", organizationId:"5fcfaf9ab349fd010e70bcfc"},
  { companyName: "Danaher", organizationId:"54a1213569702d86b63c7e02"},
  { companyName: "Gilead Sciences", organizationId:"54a11fc869702d9a8bc91702"},
  { companyName: "AutoNation", organizationId:"54a1396869702d267af36100"},
  { companyName: "Kraft Heinz", organizationId:"55f1b737f3e5bb61c9003c6b"},
  { companyName: "Avnet", organizationId:"5592201873696418d7318000"},
  { companyName: "Applied Materials", organizationId:"5ed29e6d746a300001071ff2"},
  { companyName: "Southwest Airlines", organizationId:"54a11b8569702d84c59f3f00"},
  { companyName: "Charles Schwab", organizationId:"54a1231069702da4250d6d03"},
  { companyName: "Baker Hughes", organizationId:"5da66bfcd84d9e0001e69e50"},
  { companyName: "McDonald's", organizationId:"5cabc5229faf03093ed20110"},
  { companyName: "Southern", organizationId:"54a127e369702d931362d200"},
  { companyName: "Mastercard", organizationId:"59bba885a6da985afbe18052"},
  { companyName: "Constellation Energy", organizationId:"54a1290d69702dab37218101"},
  { companyName: "Hartford Financial Services", organizationId:"5fd1a2180803f500011f46e3"},
  { companyName: "PG&E", organizationId:"6134c4114022cd00012e4a04"},
  { companyName: "Coupang", organizationId:"5da55de81f452100017dab67"},
  { companyName: "EOG Resources", organizationId:"54a1351169702d407f347100"},
  { companyName: "Union Pacific", organizationId:"54a1214169702d86b6ed8802"},
  { companyName: "Rite Aid", organizationId:"62bc256d8a9d7c00b3961c81"},
  { companyName: "Macy's", organizationId:"5ed065e67f3b450001390eb0"},
  { companyName: "Marriott International", organizationId:"54a1203f69702d9d7ed81302"},
  { companyName: "Lear", organizationId:"54a1354269702d4494608000"},
  { companyName: "Genuine Parts", organizationId:"55e17189f3e5bb3446000164"},
  { companyName: "Sherwin-Williams", organizationId:"54a1233969702da425fc8203"},
  { companyName: "Halliburton", organizationId:"5da37ab88be63400016f0d86"},
  { companyName: "Freeport-McMoRan", organizationId:"61a466729e058f00a4fb03f3"},
  { companyName: "Live Nation Entertainment", organizationId:"5f445f1aa876b800017172d4"},
  { companyName: "Marsh & McLennan", organizationId:"5d0a9d85f6512563a8b86546"},
  { companyName: "First Citizens BancShares", organizationId:"66f4e09b4518960001f2deff"},
  { companyName: "WESCO International", organizationId:"5e20606ea1d2cb01286f33c5"},
  { companyName: "Block", organizationId:"61a7f8127fea4c00de924a99"},
  { companyName: "KKR", organizationId:"54a1193869702d5010530b00"},
  { companyName: "CDW", organizationId:"54a138d769702d2fa6bd0900"},
  { companyName: "Booking Holdings", organizationId:"56e87b65f3e5bb631000818a"},
  { companyName: "Synchrony Financial", organizationId:"5ed74c3e024e5d0001af5863"},
  { companyName: "Quanta Services", organizationId:"54a1347169702d4494951700"},
  { companyName: "Jones Lang LaSalle", organizationId:"54a11bb369702da10f6d5800"},
  { companyName: "Discover Financial Services", organizationId:"54a1227369702da425773903"},
  { companyName: "Tenet Healthcare", organizationId:"55ea529ff3e5bb58f8001c3c"},
  { companyName: "Stryker", organizationId:"5ed1211cea6e0b00013193b7"},
  { companyName: "Kimberly-Clark", organizationId:"55eff1b3f3e5bb0859001037"},
  { companyName: "Waste Management", organizationId:"625854e16ebdd40114ae7373"},
  { companyName: "Cheniere Energy", organizationId:"54a23c0574686935be725b18"},
  { companyName: "Ross Stores", organizationId:"54a1349f69702d3cbb2e4c00"},
  { companyName: "WestRock", organizationId:"5e6d996a018b3b00988b0100"},
  { companyName: "General Mills", organizationId:"5d09ce5680f93e505ca8bf2e"},
  { companyName: "GE HealthCare", organizationId:"5f4db889765eb10001a333aa"},
  { companyName: "Colgate-Palmolive", organizationId:"54a1286869702d90a21a3301"},
  { companyName: "Whirlpool", organizationId:"62a105dcfc505d00df9c808e"},
  { companyName: "L3Harris Technologies", organizationId:"6258526b442862008dbc9bc8"},
  { companyName: "Adobe", organizationId:"5569502d73696425e2230200"},
  { companyName: "Becton Dickinson", organizationId:"62443a7e9528f70133415ab3"},
  { companyName: "Pioneer Natural Resources", organizationId:"5d10d0d3b624b70bf061f497"},
  { companyName: "Cognizant", organizationId:"54a122ae69702d7fe6b02503"},
  { companyName: "Murphy USA", organizationId:"54a11b3669702d94a4301f00"},
  { companyName: "Fiserv", organizationId:"5d09d8eca3ae61dfca6158e0"},
  { companyName: "Parker-Hannifin", organizationId:"5cb62919f65125ec4711b23c"},
  { companyName: "International Paper", organizationId:"5f45dd53be8f6700013c3cea"},
  { companyName: "ManpowerGroup", organizationId:"5592294a736964583ef83a00"},
  { companyName: "Aramark", organizationId:"54a11ec569702d8ed45e8b01"},
  { companyName: "Steel Dynamics", organizationId:"54a1202269702d8ccc713702"},
  { companyName: "Aflac", organizationId:"54a11f5f69702d8cccf7df01"},
  { companyName: "Tata Consultancy Services", organizationId:"5f4673254768080001bbd31c"},
  { companyName: "Tata Projects", organizationId:"54a138f569702dac84000c00"},
  { companyName: "Tata Technologies", organizationId:"54a19a0574686949e711dd00"},
  { companyName: "Infosys", organizationId:"54a1a1507468695860d04e03"},
  { companyName: "Infosys Consulting", organizationId:"54a23ab174686930c220db17"},
  { companyName: "HCLTech", organizationId:"5e58362bd5bd4a00015bc99d"},
  { companyName: "HCL Software", organizationId:"5b833afb324d446bb6c4134f"},
  { companyName: "Wipro", organizationId:"5cc2036087db610920e26ff2"},
  { companyName: "Wipro Digital", organizationId:"5d36118cee71df0927ae312b"},
  { companyName: "LTIMindtree", organizationId:"6372337ea0df8700a3ee0a71"},
  { companyName: "Tech Mahindra", organizationId:"5ed6b83cb1021800014739ea"},
  { companyName: "Persistent Systems", organizationId:"556976fa736964259cf93400"},
  { companyName: "Mphasis", organizationId:"5edae53f33043400012ba11c"},
  { companyName: "L&T Technology", organizationId: "54a12afc69702db648994f02"},
  { companyName: "Coforge", organizationId: "5f4251a2bba1ac00f6c36ead"},
  { companyName: "Tata Elxsi", organizationId:"5e55941796917c0001b8f997"},
  { companyName: "Firstsource", organizationId:"54a13a7669702d048670e100"},
  { companyName: "Affle", organizationId:"5fdb087b5e9b280001eb568b"},
  { companyName: "Cyient", organizationId: "54a1391b69702d24d34e2d00"},
  { companyName: "Newgen Software", organizationId: "5d36da8280f93e27afd416ff"},
  { companyName: "Sonata Software", organizationId:"54a122a569702d94a43e4903"},
  { companyName: "Birlasoft", organizationId: "54a1275d69702db878da3700"},
  { companyName: "Zensar", organizationId: "54a1277669702dcef9562500"},
  { companyName: "eClerx", organizationId:"54a11e7d69702da425896801"},
  { companyName: "BLS International", organizationId:"5e56126bd640ab00018f3618"},
  { companyName: "Happiest Minds", organizationId:"55923109736964583e8b5600"},
  { companyName: "Intellect Design", organizationId: "5f4db5aab63cd30001e02f9d"},
  { companyName: "Tanla Platforms Limited", organizationId:"54a1b6a87468694012fe620a"},
  { companyName: "Route Mobile", organizationId:"5b84b9bc324d444c41445519"},
  { companyName: "Aurionpro", organizationId:"54a11f1069702d88c463a201"},
  { companyName: "GitHub", organizationId:"5fc8de5191bd9400bfc52051"},
  { companyName: "Mastek", organizationId:"54a129d669702d8cfc2f0302"},
  { companyName: "Black Box", organizationId:"5f7dfbec570ed000bff817ad"},
  { companyName: "Infibeam Avenues Limited", organizationId:"64ae9a7558adfc00abe371f3"},
  { companyName: "Protean eGov", organizationId:"5a9dae82a6da98d966402de9"},
  { companyName: "eMudhra", organizationId:"5d09ee7680f93ea73c897a89"},
  { companyName: "Magellanic Cloud", organizationId:"64c4d47159904e000102ba4b"},
  { companyName: "R Systems", organizationId:"5d09b958a3ae61ab2033f068"},
];

export const signals = [
  {id: "643daa349293c1cdaa4d00f8", name: "New role"},
  {id: "643daa3c9293c1cdaa4d00f9", name: "Opened 2+ emails in past week"},
  {id: "643daa3f9293c1cdaa4d00fa", name: "Rapid growth"},
  {id: "643daa439293c1cdaa4d00fb", name: "Recent funding"},
  {id: "649f201bed59e501eb4d3f0f", name: "High buying intent"},
  {id: "649f201bed59e501eb4d3f10", name: "Merger or acquisition"},
  {id: "649f201bed59e501eb4d3f11", name: "New product or service"},
  {id: "649f201ced59e501eb4d3f12", name: "Cutting costs"},
  {id: "649f201ced59e501eb4d3f13", name: "Office expansion"},
  {id: "649f201ced59e501eb4d3f14", name: "New partnership"},
  {id: "649f201ced59e501eb4d3f15", name: "New client signed"},
  {id: "649f201ded59e501eb4d3f16", name: "Award or recognition"},
  {id: "663279c828a0230001e2338b", name: "Former champion changed jobs"},
  {id: "663279c828a0230001e2338c", name: "Recently promoted"}
];

export const technologies=[
  {"name":"Amazon Associates","uid":"amazon_associates"},
  {"name":"Amazon AWS","uid":"amazon_aws"},
  {"name":"AudioEye","uid":"audioeye"},
  {"name":"Adform","uid":"adform"},
  {"name":"Advertising.com","uid":"advertising_com"},
  {"name":"AT Internet","uid":"at_internet"},
  {"name":"Affiliate Window","uid":"affiliate_window"},
  {"name":"accessiBe","uid":"accessibe"},
  {"name":"Awin","uid":"awin"},
  {"name":"Amplitude","uid":"amplitude"},
  {"name":"Alteryx","uid":"alteryx"},
  {"name":"Atlas by Facebook","uid":"atlas_by_facebook"},
  {"name":"AdPilot","uid":"adpilot"},
  {"name":"Adition Technologies - Advertisers","uid":"adition_technologies_-_advertisers"},
  {"name":"Adara","uid":"adara"},
  {"name":"AvantLink","uid":"avantlink"},
  {"name":"AvantMetrics","uid":"avantmetrics"},
  {"name":"AppointmentPlus","uid":"appointmentplus"},
  {"name":"Affilinet","uid":"affilinet"},
  {"name":"Adzerk","uid":"adzerk"},
  {"name":"Amazon CloudWatch","uid":"amazon_cloudwatch"},
  {"name":"Bootstrap Framework","uid":"bootstrap_framework"},
  {"name":"Basis","uid":"basis"},
  {"name":"Blue Host","uid":"blue_host"},
  {"name":"Bing Ads","uid":"bing_ads"},
  {"name":"Baidu Ads","uid":"baidu_ads"},
  {"name":"Barracuda Networks","uid":"barracuda_networks"},
  {"name":"Blogger","uid":"blogger"},
  {"name":"BuddyPress","uid":"buddypress"},
  {"name":"Backbone JS Library","uid":"backbone_js_library"},
  {"name":"BigCommerce","uid":"bigcommerce"},
  {"name":"Bluekai","uid":"bluekai"},
  {"name":"Bootstrap Framework v3.2.0","uid":"bootstrap_framework_v3_2_0"},
  {"name":"Barracuda MSP","uid":"barracuda"},
  {"name":"Bootstrap Framework v3.1.1","uid":"bootstrap_framework_v3_1_1"},
  {"name":"Braintree","uid":"braintree"},
  {"name":"BugHerd","uid":"bugherd"},
  {"name":"Bitrix","uid":"bitrix"},
  {"name":"Bullhorn","uid":"bullhorn"},
  {"name":"Box","uid":"box.com"},
  {"name":"Brightcove","uid":"brightcove"},
  {"name":"Cloudinary","uid":"cloudinary"},
  {"name":"Canva","uid":"canva"},
  {"name":"CallRail","uid":"callrail"},
  {"name":"CM4All","uid":"cm4all"},
  {"name":"CloudFlare CDN","uid":"cloudflare_cdn"},
  {"name":"Content.ad","uid":"content_ad"},
  {"name":"Civic Plus","uid":"civic_plus"},
  {"name":"Century Interactive","uid":"century_interactive"},
  {"name":"Comm100","uid":"comm100"},
  {"name":"Contactatonce","uid":"contactatonce"},
  {"name":"Contact Center Solution","uid":"contact center solution"},
  {"name":"CMiC","uid":"cmic"},
  {"name":"CommentLuv","uid":"commentluv"},
  {"name":"Carchat24","uid":"carchat24"},
  {"name":"Cbox","uid":"cbox"},
  {"name":"Catylist SiteLink","uid":"catylist_sitelink"},
  {"name":"CDNetworks","uid":"cdnetworks"},
  {"name":"Catalyst.io","uid":"catalyst.io"},
  {"name":"Convio","uid":"convio"},
  {"name":"Cobalt","uid":"cobalt"},
  {"name":"DNS Made Easy","uid":"dns_made_easy"},
  {"name":"DNSPod","uid":"dnspod"},
  {"name":"DNS.com","uid":"dns_com"},
  {"name":"DNSimple","uid":"dnsimple"},
  {"name":"Dyn Managed DNS","uid":"dyn_managed_dns"},
  {"name":"Digital Ocean DNS","uid":"digital_ocean_dns"},
  {"name":"DataXu","uid":"dataxu"},
  {"name":"DataLogix","uid":"datalogix"},
  {"name":"DNS2Go","uid":"dns2go"},
  {"name":"DNSMax","uid":"dnsmax"},
  {"name":"DtDNS","uid":"dtdns"},
  {"name":"DynIP","uid":"dynip"},
  {"name":"DNSPark","uid":"dnspark"},
  {"name":"DreamHost DNS","uid":"dreamhost_dns"},
  {"name":"DoubleClick","uid":"doubleclick"},
  {"name":"DoubleClick Conversion","uid":"doubleclick_conversion"},
  {"name":"DigitalOcean","uid":"digitalocean"},
  {"name":"Disqus","uid":"disqus"},
  {"name":"Data Analytics","uid":"data analytics"},
  {"name":"Drupal","uid":"drupal"},
  {"name":"Eventbrite","uid":"eventbrite"},
  {"name":"ElasticEmail","uid":"elasticemail"},
  {"name":"Ecwid","uid":"ecwid"},
  {"name":"Emma","uid":"emma"},
  {"name":"ExactTarget","uid":"exacttarget"},
  {"name":"Epages","uid":"epages"},
  {"name":"EKM Powershop","uid":"ekm_powershop"},
  {"name":"EventsAir by Centium","uid":"eventsair_by_centium"},
  {"name":"Easy Digital Downloads","uid":"easy_digital_downloads"},
  {"name":"Elucidat","uid":"elucidat"},
  {"name":"Experient","uid":"experient"},
  {"name":"Emarsys","uid":"emarsys"},
  {"name":"Etsy","uid":"etsy"},
  {"name":"Email Attitude (1000mercis)","uid":"email_attitude_1000mercis"},
  {"name":"etouches","uid":"etouches"},
  {"name":"Edupoint","uid":"edupoint"},
  {"name":"Email Center Pro","uid":"email_center_pro"},
  {"name":"Ematch","uid":"ematch"},
  {"name":"Echo 360","uid":"echo_360"},
  {"name":"Epicor Eclipse","uid":"epicor-eclipse"},
  {"name":"Flutter","uid":"flutter"},
  {"name":"FontDeck","uid":"fontdeck"},
  {"name":"Fonts.com","uid":"fonts_com"},
  {"name":"F#","uid":"f#"},
  {"name":"Fivetran","uid":"fivetran"},
  {"name":"Facebook Login (Connect)","uid":"facebook_login"},
  {"name":"Facebook Widget","uid":"facebook_widget"},
  {"name":"Facebook Custom Audiences","uid":"facebook_web_custom_audiences"},
  {"name":"Facebook Like Button","uid":"facebook_like_button"},
  {"name":"Facebook Comments","uid":"facebook_comments"},
  {"name":"Freshdesk","uid":"freshdesk"},
  {"name":"Formstack","uid":"formstack"},
  {"name":"Flowplayer","uid":"flowplayer"},
  {"name":"FullStory","uid":"fullstory"},
  {"name":"Flashtalking","uid":"flashtalking"},
  {"name":"Flywheel","uid":"fly_wheel"},
  {"name":"F5 BIG-IP","uid":"f5_big-ip"},
  {"name":"Fastly CDN","uid":"fastly_cdn"},
  {"name":"FedEx","uid":"fedex"},
  {"name":"Facebook Social Plugins","uid":"facebook_share_button"},
  {"name":"Google Font API","uid":"google_font_api"},
  {"name":"Google Tag Manager","uid":"google_tag_manager"},
  {"name":"Google Analytics","uid":"google_analytics"},
  {"name":"Gmail","uid":"gmail"},
  {"name":"Google Apps","uid":"google_apps"},
  {"name":"Google Cloud Hosting","uid":"google_cloud_hosting"},
  {"name":"Google Maps","uid":"google_maps"},
  {"name":"Google AdSense","uid":"google_adsense"},
  {"name":"Google Maps (Non Paid Users)","uid":"google_maps_non_paid_users"},
  {"name":"Google Dynamic Remarketing","uid":"google_dynamic_remarketing"},
  {"name":"GoDaddy Hosting","uid":"godaddy_hosting"},
  {"name":"Gravity Forms","uid":"gravity_forms"},
  {"name":"Google Play","uid":"google_play"},
  {"name":"Google AdWords Conversion","uid":"google_adwords_conversion"},
  {"name":"Google Plus","uid":"google_plus_login"},
  {"name":"Google translate API","uid":"google_translate_api"},
  {"name":"Google translate widget","uid":"google_translate_widget"},
  {"name":"Gusto","uid":"gusto"},
  {"name":"Google Custom Search","uid":"google_async"},
  {"name":"Google Remarketing","uid":"google_remarketing"},
  {"name":"HostPapa","uid":"hostpapa"},
  {"name":"Hostgator","uid":"hostgator"},
  {"name":"Heroku","uid":"heroku"},
  {"name":"Hostinger","uid":"hostinger"},
  {"name":"Hetzner","uid":"hetzner"},
  {"name":"Hostway","uid":"hostway"},
  {"name":"Hosting.com","uid":"hosting_com"},
  {"name":"HostDime","uid":"hostdime"},
  {"name":"Hotjar","uid":"hotjar"},
  {"name":"Hubspot","uid":"hubspot"},
  {"name":"HeapAnalytics","uid":"heapanalytics"},
  {"name":"Highcharts JS Library","uid":"highcharts_js_library"},
  {"name":"Helpscout","uid":"helpscout"},
  {"name":"Hotmail","uid":"hotmail"},
  {"name":"Histats","uid":"histats"},
  {"name":"Highspot","uid":"highspot"},
  {"name":"Horde","uid":"horde"},
  {"name":"Hushmail","uid":"hushmail"},
  {"name":"HasOffers","uid":"hasoffers"},
  {"name":"HippoVideo","uid":"hippovideo"},
  {"name":"Insurance Services Office (ISO)","uid":"insurance services office"},
  {"name":"IoT","uid":"iot"},
  {"name":"iTunes","uid":"itunes"},
  {"name":"Intuit","uid":"intuit"},
  {"name":"Intercom","uid":"intercom"},
  {"name":"Incapsula","uid":"incapsula"},
  {"name":"Integral Ad Science","uid":"integral_ad_science"},
  {"name":"InfusionSoft","uid":"infusionsoft"},
  {"name":"iCIMS","uid":"icims"},
  {"name":"Inspectlet","uid":"inspectlet"},
  {"name":"iPerceptions","uid":"iperceptions"},
  {"name":"InMotion Hosting DNS","uid":"inmotion_hosting_dns"},
  {"name":"IBM Websphere","uid":"ibm_websphere"},
  {"name":"Infolinks","uid":"infolinks"},
  {"name":"iGoDigital","uid":"igodigital"},
  {"name":"iHomeFinder","uid":"ihomefinder"},
  {"name":"iContact","uid":"icontact"},
  {"name":"IfByPhone","uid":"ifbyphone"},
  {"name":"Iterable","uid":"iterable"},
  {"name":"iPage DNS","uid":"ipage_dns"},
  {"name":"JQuery 1.11.1","uid":"jquery_1_11_1"},
  {"name":"JQuery 2.1.1","uid":"jquery_2_1_1"},
  {"name":"Joomla","uid":"joomla"},
  {"name":"jPlayer","uid":"jplayer"},
  {"name":"JivoSite","uid":"jivosite"},
  {"name":"JW Player","uid":"jw_player"},
  {"name":"Jumpcloud","uid":"jumpcloud"},
  {"name":"Jira","uid":"jira"},
  {"name":"JTL-Shop 3","uid":"jtl-shop_3"},
  {"name":"Justworks","uid":"justworks"},
  {"name":"Jamf","uid":"jamf"},
  {"name":"Jotform","uid":"jotform"},
  {"name":"Jobvite","uid":"jobvite"},
  {"name":"JustUno","uid":"justuno"},
  {"name":"Judge.me","uid":"judge.me"},
  {"name":"JobDiva","uid":"jobdiva"},
  {"name":"Janrain","uid":"janrain"},
  {"name":"Jimdo","uid":"jimdo"},
  {"name":"JobAdder","uid":"jobadder"},
  {"name":"Java EE","uid":"java ee"},
  {"name":"Klaviyo","uid":"klaviyo"},
  {"name":"KNIME","uid":"knime"},
  {"name":"Klarna","uid":"klarna"},
  {"name":"Keen.io","uid":"keen_io"},
  {"name":"Krux","uid":"krux"},
  {"name":"Kenshoo","uid":"kenshoo"},
  {"name":"Kaltura","uid":"kaltura"},
  {"name":"KISSmetrics","uid":"kissmetrics"},
  {"name":"Kentico","uid":"kentico"},
  {"name":"Kajabi","uid":"kajabi"},
  {"name":"Kukui","uid":"kukui"},
  {"name":"Kenexa","uid":"kenexa"},
  {"name":"KnowBe4","uid":"knowbe4"},
  {"name":"Kubernetes","uid":"kubernetes"},
  {"name":"Knocommerce","uid":"knocommerce"},
  {"name":"Kicksite","uid":"kicksite"},
  {"name":"Kandji","uid":"kandji"},
  {"name":"Kiosked","uid":"kiosked"},
  {"name":"Kontera","uid":"kontera"},
  {"name":"Kayako","uid":"kayako"},
  {"name":"Leads by Web.com","uid":"leads_by_web_com"},
  {"name":"LeadForensics","uid":"leadforensics"},
  {"name":"Leadlander","uid":"leadlander"},
  {"name":"LeadExplorer","uid":"leadexplorer"},
  {"name":"Loyalty Lab","uid":"loyalty_lab"},
  {"name":"Linkedin Marketing Solutions","uid":"linkedin_display_ads__formerly_bizo"},
  {"name":"Linkedin Widget","uid":"linkedin_widget"},
  {"name":"Laravel","uid":"laravel"},
  {"name":"Linkedin Login","uid":"linkedin_login"},
  {"name":"LiveChat","uid":"livechat"},
  {"name":"Lotame","uid":"lotame"},
  {"name":"Liquidweb","uid":"liquidweb"},
  {"name":"LiveRamp","uid":"liveramp"},
  {"name":"Lucky Orange","uid":"lucky_orange"},
  {"name":"Looker","uid":"looker"},
  {"name":"Leadfeeder","uid":"leadfeeder"},
  {"name":"Linkshare","uid":"linkshare"},
  {"name":"Lightspeed","uid":"lightspeed"},
  {"name":"LearnDash","uid":"learn_dash"},
  {"name":"Lever","uid":"lever"},
  {"name":"Marketo","uid":"marketo"},
  {"name":"Mirakl","uid":"mirakl"},
  {"name":"Microsoft Dynamics 365 Marketing","uid":"microsoft_dynamics_365_marketing"},
  {"name":"Manticore","uid":"manticore"},
  {"name":"MakesBridge","uid":"makesbridge"},
  {"name":"Marketingmatic","uid":"marketingmatic"},
  {"name":"Mobile Friendly","uid":"mobile_friendly"},
  {"name":"Microsoft Office 365","uid":"office_365"},
  {"name":"Microsoft-IIS","uid":"microsoft-iis"},
  {"name":"MailChimp","uid":"mailchimp"},
  {"name":"Mailchimp Mandrill","uid":"mailchimp_mandrill"},
  {"name":"MailChimp SPF","uid":"mailchimp_spf"},
  {"name":"Micro","uid":"micro"},
  {"name":"Microsoft Azure Hosting","uid":"microsoft"},
  {"name":"Multilingual","uid":"multilingual"},
  {"name":"MailJet","uid":"mailjet"},
  {"name":"Mimecast","uid":"mimecast"},
  {"name":"Magento","uid":"magento"},
  {"name":"Media.net","uid":"media_net"},
  {"name":"Mixpanel","uid":"mixpanel"},
  {"name":"Nginx","uid":"nginx"},
  {"name":"Node.js","uid":"node.js"},
  {"name":"NSOne","uid":"nsone"},
  {"name":"New Relic","uid":"new_relic"},
  {"name":"Netlify","uid":"netlify"},
  {"name":"NetSuite","uid":"netsuite"},
  {"name":"Nielsen Display Ads (Formerly eXelate)","uid":"nielsen_display_ads_formerly_exelate"},
  {"name":"Nativo","uid":"nativo"},
  {"name":"Nielsen NetRatings","uid":"nielsen_netratings"},
  {"name":"Navegg","uid":"navegg"},
  {"name":"Netskope","uid":"netskope"},
  {"name":"Nosto","uid":"nosto"},
  {"name":"Network Solutions Seal","uid":"network_solutions_seal"},
  {"name":"Netnames Cedel","uid":"netnames_cedel"},
  {"name":"Netriplex","uid":"netriplex"},
  {"name":"NationBuilder","uid":"nationbuilder"},
  {"name":"NetSuite E-commerce","uid":"netsuite_e-commerce"},
  {"name":"NMU AB","uid":"nmu_ab"},
  {"name":"Newton Software","uid":"newton_software"},
  {"name":"Notion","uid":"notion"},
  {"name":"Optimizely","uid":"optimizely"},
  {"name":"OpenID","uid":"openid"},
  {"name":"Ooyala","uid":"ooyala"},
  {"name":"Oracle Products","uid":"oracle products"},
  {"name":"Ometria","uid":"ometria"},
  {"name":"Okta (sub-domains only)","uid":"okta_sub-domains_only"},
  {"name":"Optimost","uid":"optimost"},
  {"name":"Onswipe","uid":"onswipe"},
  {"name":"Oracle E Business Suite","uid":"oracle e business suite"},
  {"name":"Oasis-7","uid":"oasis-7"},
  {"name":"Outlook","uid":"outlook"},
  {"name":"OpenSSL","uid":"openssl"},
  {"name":"OpenX - Exchange","uid":"openx_-_exchange"},
  {"name":"Omniture (Adobe)","uid":"omniture_adobe"},
  {"name":"Oracle Cloud","uid":"oracle_cloud"},
  {"name":"OneTrust","uid":"onetrust"},
  {"name":"Open AdStream (Appnexus)","uid":"open_adstream_appnexus"},
  {"name":"Olark","uid":"olark"},
  {"name":"Outbrain","uid":"outbrain"},
  {"name":"OpenCart","uid":"opencart"},
  {"name":"Paypal","uid":"paypal"},
  {"name":"Parse.ly","uid":"parse_ly"},
  {"name":"PayU","uid":"payu"},
  {"name":"PayPal Credit","uid":"paypal_credit"},
  {"name":"Polar (Media Voice)","uid":"polar"},
  {"name":"Personyze","uid":"personyze"},
  {"name":"PaySimple","uid":"paysimple"},
  {"name":"Peerius","uid":"peerius"},
  {"name":"Paylocity","uid":"paylocity"},
  {"name":"Paychex","uid":"paychex"},
  {"name":"Python","uid":"python"},
  {"name":"Piwik","uid":"piwik"},
  {"name":"Phoenix","uid":"phoenix"},
  {"name":"PHP 5.3","uid":"php_5_3"},
  {"name":"Proofpoint","uid":"proofpoint"},
  {"name":"Pardot","uid":"pardot"},
  {"name":"PrestaShop","uid":"prestashop"},
  {"name":"PubMatic","uid":"pubmatic"},
  {"name":"Phusion Passenger","uid":"phusion_passenger"},
  {"name":"Postmark","uid":"postmark"},
  {"name":"Quantcast","uid":"quantcast"},
  {"name":"QuickBooks","uid":"quickbooks"},
  {"name":"Qualtrics","uid":"qualtrics_intercept"},
  {"name":"Qlik Sense","uid":"qlik sense"},
  {"name":"Quandoo","uid":"quandoo"},
  {"name":"Quickbooks Online","uid":"quickbooks_online"},
  {"name":"Qualaroo","uid":"qualaroo"},
  {"name":"QuadPay","uid":"quadpay"},
  {"name":"Questback","uid":"questback"},
  {"name":"Qubit OpenTag","uid":"qubit_opentag"},
  {"name":"Quartic","uid":"quartic"},
  {"name":"Quadia","uid":"quadia"},
  {"name":"Qubit Deliver","uid":"qubit_deliver"},
  {"name":"Quickbooks Commerce","uid":"quickbooks_commerce"},
  {"name":"QRATOR","uid":"qrator"},
  {"name":"QuoteValet","uid":"quotevalet"},
  {"name":"RTB House","uid":"rtb_house"},
  {"name":"Reservit","uid":"reservit"},
  {"name":"Resumator","uid":"resumator"},
  {"name":"ReTargeter","uid":"retargeter"},
  {"name":"ResDiary","uid":"resdiary"},
  {"name":"RestaurantConnect","uid":"restaurantconnect"},
  {"name":"Restorando","uid":"restorando"},
  {"name":"Recruiterbox","uid":"recruiterbox"},
  {"name":"Realtime Targeting","uid":"realtime_targeting"},
  {"name":"reCAPTCHA","uid":"recaptcha"},
  {"name":"Remote","uid":"remote"},
  {"name":"Render","uid":"render"},
  {"name":"Reviews","uid":"reviews"},
  {"name":"Route 53","uid":"route_53"},
  {"name":"Ruby On Rails","uid":"ruby_on_rails"},
  {"name":"Rackspace MailGun","uid":"rackspace_mailgun"},
  {"name":"React Native","uid":"react native"},
  {"name":"Rackspace Email","uid":"rackspace_email"},
  {"name":"React","uid":"react"},
  {"name":"Rackspace","uid":"rackspace"},
  {"name":"ShareThis","uid":"sharethis"},
  {"name":"Sophos","uid":"sophos"},
  {"name":"Sonobi","uid":"sonobi"},
  {"name":"Sitelock","uid":"sitelock"},
  {"name":"Sift Science","uid":"sift_science"},
  {"name":"Starfield","uid":"starfield"},
  {"name":"SurveyMonkey","uid":"surveymonkey"},
  {"name":"SurveyGizmo","uid":"surveygizmo"},
  {"name":"SaleCycle","uid":"salecycle"},
  {"name":"Swiftype","uid":"swiftype"},
  {"name":"Stackla","uid":"stackla"},
  {"name":"SLI Systems","uid":"sli_systems"},
  {"name":"SocialTwist","uid":"socialtwist"},
  {"name":"Spigit (Mindjet)","uid":"spigit_mindjet"},
  {"name":"ScribbleLive","uid":"scribblelive"},
  {"name":"SOAP Vault","uid":"soap_vault"},
  {"name":"SearchDex","uid":"searchdex"},
  {"name":"Surveypal","uid":"surveypal"},
  {"name":"Spring Metrics","uid":"spring_metrics"},
  {"name":"SocialPlus","uid":"socialplus"},
  {"name":"Tealium","uid":"tealium"},
  {"name":"Tag Commander","uid":"tag_commander"},
  {"name":"TagMan","uid":"tagman"},
  {"name":"Typekit","uid":"typekit"},
  {"name":"TikTok","uid":"tiktok"},
  {"name":"Trustpilot","uid":"trustpilot"},
  {"name":"The Trade Desk","uid":"the_trade_desk"},
  {"name":"Twitter Advertising","uid":"twitter_advertising"},
  {"name":"Toast","uid":"toast"},
  {"name":"Taboola","uid":"taboola"},
  {"name":"Twilio","uid":"twilio"},
  {"name":"Teads","uid":"teads"},
  {"name":"TripleLift","uid":"triplelift"},
  {"name":"TYPO3","uid":"typo3"},
  {"name":"TrustedShops","uid":"trustedshops"},
  {"name":"Tableau","uid":"tableau"},
  {"name":"Typeform","uid":"typeform"},
  {"name":"Twitter Sharing","uid":"twitter_sharing"},
  {"name":"TurboSMTP","uid":"turbosmtp"},
  {"name":"Taboola Newsroom","uid":"taboola_newsroom"},
  {"name":"Ubuntu","uid":"ubuntu"},
  {"name":"UPS","uid":"ups"},
  {"name":"Uipath","uid":"uipath"},
  {"name":"Unruly Media","uid":"unruly_media"},
  {"name":"UltraDns","uid":"ultradns"},
  {"name":"UK Fast Hosting","uid":"uk_fast_hosting"},
  {"name":"UltiPro","uid":"ultipro"},
  {"name":"Undertone","uid":"undertone"},
  {"name":"UptimeRobot","uid":"uptimerobot"},
  {"name":"UserLike","uid":"userlike"},
  {"name":"Upfluence","uid":"upfluence"},
  {"name":"Umbraco","uid":"umbraco"},
  {"name":"UserVoice","uid":"uservoice"},
  {"name":"Unreal Engine","uid":"unreal_engine"},
  {"name":"Upsellit","uid":"upsellit"},
  {"name":"UberFlip","uid":"uberflip"},
  {"name":"UserReport","uid":"userreport"},
  {"name":"Umantis","uid":"umantis"},
  {"name":"UpCloud","uid":"upcloud"},
  {"name":"User Trust (Comodo)","uid":"user_trust_comodo"},
  {"name":"Videology","uid":"videology"},
  {"name":"Videoplaza","uid":"videoplaza"},
  {"name":"Virool","uid":"virool"},
  {"name":"Varnish","uid":"varnish"},
  {"name":"Vimeo","uid":"vimeo"},
  {"name":"VueJS","uid":"vue_js_library"},
  {"name":"Visual Website Optimizer","uid":"visual_website_optimizer"},
  {"name":"Viewpoint","uid":"viewpoint"},
  {"name":"Vonage","uid":"vonage"},
  {"name":"Vagaro","uid":"vagaro"},
  {"name":"Vercel","uid":"vercel"},
  {"name":"Vincere","uid":"vincere"},
  {"name":"Virtuemart","uid":"virtuemart"},
  {"name":"Vzaar","uid":"vzaar"},
  {"name":"Vidyard","uid":"vidyard"},
  {"name":"Volusion","uid":"volusion"},
  {"name":"Visual Basic","uid":"visual basic"},
  {"name":"VideoJS","uid":"videojs"},
  {"name":"VigLink","uid":"viglink"},
  {"name":"Verisign Seal","uid":"verisign_seal"},
  {"name":"Webex","uid":"webex"},
  {"name":"WebinarJam","uid":"webinarjam"},
  {"name":"Webo","uid":"webo"},
  {"name":"WordPress.org","uid":"wordpress_org"},
  {"name":"Wix","uid":"wix"},
  {"name":"Woo Commerce","uid":"woo_commerce"},
  {"name":"Wordpress.com","uid":"wordpress_com"},
  {"name":"Weebly","uid":"weebly"},
  {"name":"Webflow","uid":"webflow"},
  {"name":"Webmail","uid":"webmail"},
  {"name":"WP Engine","uid":"wp_engine"},
  {"name":"Wistia","uid":"wistia"},
  {"name":"Wufoo","uid":"wufoo"},
  {"name":"Workday Recruit","uid":"workday_recruit"},
  {"name":"Webtraxs","uid":"webtraxs"},
  {"name":"Workable","uid":"workable"},
  {"name":"Woopra","uid":"woopra"},
  {"name":"Weborama","uid":"weborama"},
  {"name":"Woo Commerce Memberships","uid":"woo_ecommerce_memberships"},
  {"name":"Wishpond","uid":"wishpond"},
  {"name":"Xamarin","uid":"xamarin"},
  {"name":"Xt-commerce","uid":"xt-commerce"},
  {"name":"Xero","uid":"xero"},
  {"name":"XiTi","uid":"xiti"},
  {"name":"Xplosion","uid":"xplosion"},
  {"name":"X-Cart","uid":"x-cart"},
  {"name":"Xenforo","uid":"xenforo"},
  {"name":"Xceligent","uid":"xceligent"},
  {"name":"Xplosion Interactive","uid":"xplosion_interactive"},
  {"name":"XO Communications","uid":"xo_communications"},
  {"name":"Xinnet","uid":"xinnet"},
  {"name":"XXL webhosting","uid":"xxl_webhosting"},
  {"name":"Xtium","uid":"xtium"},
  {"name":"Xand","uid":"xand"},
  {"name":"YouTube","uid":"youtube"},
  {"name":"Yelp","uid":"yelp"},
  {"name":"Yandex Metrica","uid":"yandex_metrika"},
  {"name":"Yahoo Analytics","uid":"yahoo_analytics"},
  {"name":"Yotpo","uid":"yotpo"},
  {"name":"Yahoo Ad Manager Plus","uid":"yahoo_ad_manager_plus"},
  {"name":"Yardi","uid":"yardi"},
  {"name":"Yola","uid":"yola"},
  {"name":"Yext","uid":"yext"},
  {"name":"Yahoo Tag Manager","uid":"yahoo_tag_manager"},
  {"name":"Yahoo Retargeting","uid":"yahoo_retargeting_japan"},
  {"name":"Yahoo Mail","uid":"yahoo_mail"},
  {"name":"Yodle","uid":"yodle"},
  {"name":"Yandex.Direct","uid":"yandex_direct"},
  {"name":"Yieldify","uid":"yieldify"},
  {"name":"Yahoo Store","uid":"yahoo_store"},
  {"name":"YuMe","uid":"yume"},
  {"name":"YouCanBook.me","uid":"youcanbook_me"},
  {"name":"YieldBot","uid":"yieldbot"},
  {"name":"YayPay","uid":"yaypay"},
  {"name":"Zendesk","uid":"zendesk"},
  {"name":"ZoomInfo","uid":"zoominfo"},
  {"name":"Zopim","uid":"zopim"},
  {"name":"Zencoder","uid":"zencoder"},
  {"name":"Zoho Email","uid":"zoho_email"},
  {"name":"Zoho CRM","uid":"zoho_crm"},
  {"name":"ZocDoc","uid":"zocdoc"},
  {"name":"Zoho SalesIQ","uid":"zoho_sales_iq"},
  {"name":"Zoho One","uid":"zoho one"},
  {"name":"Zemanta","uid":"zemanta"},
  {"name":"Zoho Creator","uid":"zoho creator"},
  {"name":"ZoneEdit","uid":"zoneedit"},
  {"name":"Zscaler","uid":"zscaler"},
  {"name":"Zoom Webinar","uid":"zoom webinar"},
  {"name":"Zoho Books","uid":"zoho_books"},
  {"name":"Zen Planner","uid":"zen_planner"},
  {"name":"Zimbra","uid":"zimbra"},
  {"name":"Zanox","uid":"zanox"},
  {"name":"Zergnet","uid":"zergnet"},
  {"name":"Zapier","uid":"zapier"}
  ];