export interface InputType {
  id: string;
  text: string | number;
}

export const orgLocations: string[] = [
  "Americas",
  "APAC",
  "Asia",
  "Australia",
  "Arizona, US",
  "Atlanta, Georgia",
  "Alabama, US",
  "Austin, Texas",
  "Alberta, Canada",
  "Alexandria, Virginia",
  "Amsterdam, Netherlands",
  "Arkansas, US",
  "Antwerp, Belgium",
  "Austria",
  "Auvergne-Rhône-Alpes, France",
  "Aquitaine-Limousin-Poitou-Charentes, France",
  "Argentina",
  "Ahmedabad, India",
  "Aquitaine, France",
  "Albuquerque, New Mexico",
  "Bavaria, Germany",
  "Baden-Württemberg, Germany",
  "Belgium",
  "Berlin, Germany",
  "Bangkok, Thailand",
  "Brazil",
  "Beijing, China",
  "Bengaluru, India",
  "Boston, Massachusetts",
  "British Columbia, Canada",
  "Bogota, Colombia",
  "Brussels, Belgium",
  "Baltimore, Maryland",
  "Bremen, Germany",
  "Buffalo/Niagara, New York Area",
  "Bergen, Germany",
  "Brandenburg, Germany",
  "Birmingham, United Kingdom",
  "Baden-Baden, Germany",
  "Bucharest, Romania",
  "China",
  "Canada",
  "California, US",
  "Chicago, Illinois",
  "Czech Republic",
  "Chennai, India",
  "Colombia",
  "Charlotte, North Carolina",
  "Clamart, France",
  "Cincinnati, Ohio",
  "Columbus, Ohio",
  "Cologne, Germany",
  "Cleveland, Ohio",
  "Calgary, Canada",
  "Cape Town, South Africa",
  "Columbia, South Carolina",
  "Colorado Springs, Colorado",
  "Cambridge, Massachusetts",
  "Chengdu, China",
  "Chattanooga, Tennessee",
  "Chantilly, Virginia",
  "Dallas/Fort Worth Area",
  "Delhi, India",
  "Dallas, Texas",
  "District of Columbia, US",
  "Denver, Colorado",
  "Dublin, Ireland",
  "Dubai, United Arab Emirates",
  "Detroit, Michigan",
  "Düsseldorf, Germany",
  "Delaware, US",
  "Dresden, Germany",
  "Doha, Qatar",
  "Dayton, Ohio",
  "Durham, North Carolina",
  "Denmark",
  "Dortmund, Germany",
  "Des Moines, Iowa",
  "Dearborn, Michigan",
  "Darmstadt, Germany",
  "Deerfield Beach, Florida",
  "EMEA",
  "Europe",
  "European Union",
  "England, United Kingdom",
  "Estado de México, Mexico",
  "Edmonton, Canada",
  "Eindhoven, Netherlands",
  "Essen, Germany",
  "Englewood, Colorado",
  "Edinburgh, United Kingdom",
  "El Paso, Texas",
  "Emilia-Romagna, Italy",
  "Edison, New Jersey",
  "El Segundo, California",
  "Ernakulam, India",
  "Eden Prairie, Minnesota",
  "Evansville, Indiana",
  "Egypt",
  "Erfurt, Germany",
  "Everett, Washington",
  "France",
  "Florida, US",
  "Flanders, Belgium",
  "Frankfurt, Germany",
  "Fort Worth, Texas",
  "Fort Lauderdale, Florida",
  "Federal Territory of Kuala Lumpur, Malaysia",
  "Finland",
  "Fairfax, Virginia",
  "Fujian, China",
  "Fort Myers, Florida",
  "Fresno, California",
  "Federal Capital Territory, Nigeria",
  "Federal District, Mexico",
  "Fort Wayne, Indiana",
  "Falls Church, Virginia",
  "Fremont, California",
  "Freiburg, Germany",
  "Fargo, North Dakota",
  "Fuzhou, China",
  "Greater Houston Area",
  "Germany",
  "Greater Denver Area",
  "Greater Los Angeles Area",
  "Greater Philadelphia Area",
  "Greater New York City Area",
  "Greater Memphis Area",
  "Greater Atlanta Area",
  "Greater Milwaukee Area",
  "Greater St. Louis Area",
  "Greater Chicago Area",
  "Greater Seattle Area",
  "Greater Boston Area",
  "Georgia, US",
  "Greater Minneapolis-St. Paul Area",
  "Greater San Diego Area",
  "Greater Salt Lake City Area",
  "Greater Nashville Area",
  "Greater Omaha Area",
  "Guangdong, China",
  "Hamburg, Germany",
  "Hesse, Germany",
  "Houston, Texas",
  "Haryana, India",
  "Hong Kong",
  "Hyderabad, India",
  "Hanoi, Vietnam",
  "Hanover, Germany",
  "Hawaii, US",
  "Hangzhou, China",
  "Ho Chi Minh City, Vietnam",
  "Ho Chi Minh, Vietnam",
  "Hoograven, Netherlands",
  "Hlavní město Praha, Czech Republic",
  "Hubei, China",
  "Honolulu, Hawaii",
  "Hartford, Connecticut",
  "Herndon, Virginia",
  "Huntsville, Alabama",
  "Hungary",
  "India",
  "Illinois, US",
  "Indiana, US",
  "Iowa, US",
  "Italy",
  "Indianapolis, Indiana",
  "Ireland",
  "Israel",
  "Indonesia",
  "Idaho, US",
  "Irvine, California",
  "Indore, India",
  "Irving, Texas",
  "İstanbul, Turkey",
  "Ingolstadt, Germany",
  "Irkutsk Oblast, Russia",
  "Irkutsk, Russia",
  "Ibaraki Prefecture, Japan",
  "Ilfov County, Romania",
  "Izhevsk, Russia",
  "Japan",
  "Jerusalem, Israel",
  "Jiangsu, China",
  "Jacksonville, Florida",
  "Jalisco, Mexico",
  "Jakarta, Indonesia",
  "Johannesburg, South Africa",
  "Jersey City, New Jersey",
  "Jilin, China",
  "Jaipur, India",
  "Jackson, Mississippi",
  "Jonkoping County, Sweden",
  "Jiangxi, China",
  "Jharkhand, India",
  "Jinan, China",
  "Juriquilla, Mexico",
  "Joliet, Illinois",
  "Jeddah, Saudi Arabia",
  "Jackson, Michigan",
  "Jinhua, China",
  "Karnataka, India",
  "Kentucky, US",
  "Kansas, US",
  "Kansas City, Missouri",
  "Krasnodar Krai, Russia",
  "Kerala, India",
  "Krakow, Poland",
  "Karlsruhe, Germany",
  "Kanagawa Prefecture, Japan",
  "Knoxville, Tennessee",
  "Kuala Lumpur, Malaysia",
  "Koog aan de Zaan, Netherlands",
  "Kortrijk, Belgium",
  "Krasnodar, Russia",
  "Kazan, Russia",
  "Kansas City, Kansas",
  "Krasnoyarsk Krai, Russia",
  "Kolkata, India",
  "Kuwait",
  "Kyiv city, Ukraine",
  "Lisbon, Portugal",
  "Los Angeles, California",
  "Lower Saxony, Germany",
  "Louisiana, US",
  "Lagos, Nigeria",
  "London, United Kingdom",
  "Lima, Peru",
  "Louisville, Kentucky",
  "Lower Silesian Voivodeship, Poland",
  "Lesser Poland Voivodeship, Poland",
  "Leipzig, Germany",
  "Leeds, United Kingdom",
  "Limburg, Netherlands",
  "Lombardy, Italy",
  "Lyon, France",
  "Liaoning, China",
  "Littleton, Colorado",
  "Long Beach, California",
  "Lexington, Kentucky",
  "Leicester, United Kingdom",
  "Miami/Fort Lauderdale Area",
  "Moscow, Russia",
  "Massachusetts, US",
  "Mexico",
  "Michigan, US",
  "Maryland, US",
  "Maharashtra, India",
  "Minnesota, US",
  "Missouri, US",
  "Mumbai, India",
  "Munich, Germany",
  "Minneapolis, Minnesota",
  "Miami, Florida",
  "Moscow Oblast, Russia",
  "Masovian Voivodeship, Poland",
  "Melbourne, Australia",
  "Milwaukee, Wisconsin",
  "Mississippi, US",
  "Maine, US",
  "Manchester, United Kingdom",
  "North America",
  "New York, US",
  "Netherlands",
  "New York, New York",
  "North Rhine-Westphalia, Germany",
  "North Carolina, US",
  "New Jersey, US",
  "New Delhi, India",
  "North Holland, Netherlands",
  "New South Wales, Australia",
  "Nevada, US",
  "Nebraska, US",
  "North Brabant, Netherlands",
  "Nigeria",
  "New Hampshire, US",
  "New Mexico, US",
  "Nashville, Tennessee",
  "Nalgonda, India",
  "Nord-Pas-de-Calais, France",
  "North Dakota, US",
  "Ohio, US",
  "Ontario, Canada",
  "Oregon, US",
  "Oklahoma, US",
  "Overijssel, Netherlands",
  "Orlando, Florida",
  "Omaha, Nebraska",
  "Oklahoma City, Oklahoma",
  "Oakland, California",
  "Ottawa, Canada",
  "Osaka Prefecture, Japan",
  "Orange, California",
  "Overland Park, Kansas",
  "Osaka, Japan",
  "Oslo, Norway",
  "Olomouc Region, Czech Republic",
  "Osnabrück, Germany",
  "Omsk Oblast, Russia",
  "Omsk, Russia",
  "Oxford, United Kingdom",
  "Pennsylvania, US",
  "Poland",
  "Portugal",
  "Pune, India",
  "Phoenix, Arizona",
  "Philadelphia, Pennsylvania",
  "Pays de la Loire, France",
  "Portland, Oregon",
  "Paris, France",
  "Pittsburgh, Pennsylvania",
  "Provence-Alpes-Côte d'Azur, France",
  "Philippines",
  "Peru",
  "Porto, Portugal",
  "Porto District, Portugal",
  "Prague, Czech Republic",
  "Palo Alto, California",
  "Plano, Texas",
  "Puebla, Mexico",
  "Puerto Rico",
  "Quebec, Canada",
  "Queensland, Australia",
  "Qatar",
  "Quebec City, Canada",
  "Querétaro, Mexico",
  "Québec, Canada",
  "Qingdao, China",
  "Quincy, Massachusetts",
  "Quezon City, Philippines",
  "Quanzhou, China",
  "Quantico, Virginia",
  "Quimper, France",
  "Quincy, Illinois",
  "Queensbury, New York",
  "Quintana Roo, Mexico",
  "Quincy-sous-Sénart, France",
  "Qinghai, China",
  "Qiqiha'er, China",
  "Quincy, California",
  "Qujing, China",
  "Russia",
  "Rhineland-Palatinate, Germany",
  "Romania",
  "Rhone-Alpes, France",
  "Raleigh, North Carolina",
  "Richmond, Virginia",
  "Rhode Island, US",
  "Rotterdam, Netherlands",
  "Riyadh, Saudi Arabia",
  "Riyadh Province, Saudi Arabia",
  "Reston, Virginia",
  "Rajasthan, India",
  "Rostov Oblast, Russia",
  "Rockville, Maryland",
  "Reno, Nevada",
  "Rochester, New York",
  "Rio de Janeiro, Brazil",
  "Republic of Bashkortostan, Russia",
  "Rhône-Alpes, France",
  "Redwood City, California",
  "Shanghai, China",
  "Saint Petersburg, Russia",
  "South Carolina, US",
  "State of São Paulo, Brazil",
  "Saxony, Germany",
  "South Holland, Netherlands",
  "Stockholm County, Sweden",
  "Scotland, United Kingdom",
  "Schleswig-Holstein, Germany",
  "Saxony-Anhalt, Germany",
  "San Juan, Puerto Rico",
  "Samara Oblast, Russia",
  "Silesian Voivodeship, Poland",
  "Samut Prakan, Thailand",
  "Sverdlovsk Oblast, Russia",
  "South Dakota, US",
  "State of Rio de Janeiro, Brazil",
  "Sichuan, China",
  "Shandong, China",
  "South Moravian Region, Czech Republic",
  "Texas, US",
  "Thailand",
  "Tampa/St. Petersburg, Florida Area",
  "Tennessee, US",
  "Tamil Nadu, India",
  "Telangana, India",
  "Taiwan",
  "Toronto, Canada",
  "Tampa, Florida",
  "Turkey",
  "Taipei, Taiwan",
  "Thuringia, Germany",
  "Tianjin, China",
  "Tucson, Arizona",
  "Tulsa, Oklahoma",
  "Tatarstan, Russia",
  "Tokyo, Japan",
  "Tallahassee, Florida",
  "Tempe, Arizona",
  "Troy, Michigan",
  "United States",
  "United Kingdom",
  "Utah, US",
  "Uttar Pradesh, India",
  "Utrecht, Netherlands",
  "United Arab Emirates",
  "Ukraine",
  "Ulm, Germany",
  "Ufa, Russia",
  "Uppsala County, Sweden",
  "Uusimaa, Finland",
  "Udmurt Republic, Russia",
  "Ulyanovsk Oblast, Russia",
  "Udmurtskaja Respublika, Russia",
  "Uppsala, Sweden",
  "Ulyanovsk, Russia",
  "Upper Austria, Austria",
  "Uttarakhand, India",
  "Upper Normandy, France",
  "Urbana, Illinois",
  "Virginia, US",
  "Vietnam",
  "Victoria, Australia",
  "Västra Götaland County, Sweden",
  "Vancouver, Canada",
  "Vienna, Austria",
  "Vlaanderen, Belgium",
  "Vermont, US",
  "Valle de Chalco Solidaridad, Mexico",
  "Virginia Beach, Virginia",
  "Veracruz, Mexico",
  "Voronezh Oblast, Russia",
  "Voronezh, Russia",
  "Vilvoorde, Belgium",
  "Volgograd Oblast, Russia",
  "Vancouver, Washington",
  "Versailles, France",
  "Valencian Community, Spain",
  "Vladimir Oblast, Russia",
  "Vienna, Virginia",
  "Washington D.C. Metro Area",
  "Washington, US",
  "Wisconsin, US",
  "Washington, District of Columbia",
  "Wetering, Netherlands",
  "West Virginia, US",
  "Warsaw, Poland",
  "Western Cape, South Africa",
  "Wrocław, Poland",
  "Wales, United Kingdom",
  "Wyoming, US",
  "Western Australia, Australia",
  "Wuhan, China",
  "Walloon Region, Belgium",
  "Wichita, Kansas",
  "Whitby, Canada",
  "Winnipeg, Canada",
  "Worcester, Massachusetts",
  "West Palm Beach, Florida",
  "West Bengal, India",
  "Xi'an, China",
  "Xenia, Ohio",
  "Xuzhou, China",
  "Xining, China",
  "Xiaogan, China",
  "Xingtai, China",
  "Xizang (Tibet), China",
  "Xinjiang, China",
  "Xiamen, China",
  "Xanten, Germany",
  "Xanxerê, Brazil",
  "Xambioá, Brazil",
  "Xinjiang Weiwuerzizhiqu, China",
  "Xicoténcatl, Mexico",
  "Xilxes, Spain",
  "Xenia, Illinois",
  "Xalapa, Mexico",
  "Xochihuehuetlán, Mexico",
  "Xàtiva, Spain",
  "Xirivella, Spain",
  "Yekaterinburg, Russia",
  "York, Pennsylvania",
  "Yokohama, Japan",
  "Yaroslavl Oblast, Russia",
  "Yaroslavl, Russia",
  "Youngstown, Ohio",
  "Yucatán, Mexico",
  "Ypenburg, Netherlands",
  "Ypres, Belgium",
  "Yonkers, New York",
  "Yuma, Arizona",
  "Yamalo-Nenets Autonomous Okrug, Russia",
  "Yucaipa, California",
  "Yamaguchi Prefecture, Japan",
  "Yakima, Washington",
  "Yantai, China",
  "Yunnan, China",
  "Ypsilanti, Michigan",
  "York, United Kingdom",
  "Yoshkar-Ola, Russia",
  "Zhejiang, China",
  "Zurich, Switzerland",
  "Zürich, Switzerland", // Note: "Zurich" and "Zürich" are the same location, with different spellings.
  "Zuid-Holland, Netherlands",
  "Zapopan, Mexico",
  "Zeeland, Netherlands",
  "Zwolle, Netherlands",
  "Zhuhai, China",
  "Zlin Region, Czech Republic",
  "Zelenograd, Russia",
  "Zaventem, Belgium",
  "Zaandam, Netherlands",
  "Zwickau, Germany",
  "Zaragoza, Spain",
  "Zionsville, Indiana",
  "Zabaykalsky Krai, Russia",
  "Zanesville, Ohio",
  "Zielona Gora, Poland",
  "Zunyi, China",
  "Zephyrhills, Florida",
];

export const jobTitles: string[] = [
  "Account Manager",
  "Associate",
  "Administrative Assistant",
  "Accountant",
  "Account Executive",
  "Assistant Manager",
  "Analyst",
  "Assistant Professor",
  "Associate Professor",
  "Administrator",
  "Attorney",
  "Agent",
  "Area Manager",
  "Administrativo",
  "Architect",
  "Admin",
  "Auditor",
  "Assistant",
  "Analista",
  "Associate Director",
  "Business Analyst",
  "Business Development Manager",
  "Branch Manager",
  "Business Manager",
  "Buyer",
  "Business Development",
  "Broker",
  "Banker",
  "Business Development Executive",
  "Business Consultant",
  "Brand Manager",
  "Bookkeeper",
  "Barista",
  "Broker Associate",
  "Bartender",
  "Board Member",
  "Business Development Director",
  "Business",
  "Business Owner",
  "Boss",
  "Consultant",
  "CEO",
  "Customer Service",
  "Controller",
  "Customer Service Representative",
  "Cashier",
  "CFO",
  "CSR",
  "Clerk",
  "Civil Engineer",
  "Coordinator",
  "Creative Director",
  "Customer Service Manager",
  "Chef",
  "Co-Founder",
  "Chief Operating Officer",
  "Consultor",
  "Chief Financial Officer",
  "Case Manager",
  "Captain",
  "Director",
  "Docente",
  "Designer",
  "Developer",
  "Design Engineer",
  "Driver",
  "District Manager",
  "Director of Operations",
  "Doctor",
  "Deputy Manager",
  "Directeur",
  "Director of Sales",
  "Data Analyst",
  "Dr",
  "District Sales Manager",
  "Director of Marketing",
  "Diretor",
  "Director of Business Development",
  "Development Manager",
  "Department Manager",
  "Engineer",
  "Executive Assistant",
  "Executive Director",
  "Executive",
  "Electrical Engineer",
  "Educator",
  "Empleado",
  "Editor",
  "Engineering Manager",
  "Electrician",
  "Estudiante",
  "Employee",
  "Estudante",
  "English Teacher",
  "Enseignante",
  "Enseignant",
  "Empleada",
  "Executive Vice President",
  "Economist",
  "Executive Secretary",
  "Financial Analyst",
  "Financial Advisor",
  "Finance Manager",
  "Founder",
  "Financial Controller",
  "Flight Attendant",
  "Finance",
  "Founder and CEO",
  "Field Engineer",
  "Finance Director",
  "Field Service Engineer",
  "Faculty",
  "Financial Consultant",
  "Facilities Manager",
  "Funzionario",
  "Financial Manager",
  "Financial Representative",
  "Foreman",
  "Financial Planner",
  "Facility Manager",
  "General Manager",
  "Gerente",
  "Graphic Designer",
  "Graduate Student",
  "Graduate Research Assistant",
  "Gerente Comercial",
  "GM",
  "Graduate Assistant",
  "Graduate Teaching Assistant",
  "Geologist",
  "Gerente General",
  "Group Leader",
  "General Counsel",
  "Geschäftsführer",
  "Gepensioneerd",
  "Geometra",
  "Gerente de Projetos",
  "Group Manager",
  "Graphic Artist",
  "Gerente de Vendas",
  "HR Manager",
  "HR",
  "Human Resources Manager",
  "Human Resources",
  "HR Business Partner",
  "HR Executive",
  "HR Specialist",
  "HR Generalist",
  "HR Assistant",
  "HR Officer",
  "HR Consultant",
  "HR Coordinator",
  "HR Director",
  "Human Resources Generalist",
  "HR Advisor",
  "HR Administrator",
  "Human Resources Specialist",
  "Housewife",
  "Homemaker",
  "Human Resource Manager",
  "Intern",
  "Instructor",
  "IT Manager",
  "Impiegato",
  "IT",
  "Impiegata",
  "IT Specialist",
  "IT Consultant",
  "Insurance Agent",
  "Independent Consultant",
  "IT Analyst",
  "Inside Sales",
  "Internal Auditor",
  "IT Project Manager",
  "Inspector",
  "Internship",
  "Independent Distributor",
  "Interior Designer",
  "Insegnante",
  "Inside Sales Representative",
  "Journalist",
  "Java Developer",
  "Jubilado",
  "Jefe",
  "Junior Consultant",
  "Journaliste",
  "Junior Engineer",
  "Jubilada",
  "Juriste",
  "Jefe de Proyectos",
  "Jefe de Proyecto",
  "Jefe de Departamento",
  "Jornalista",
  "Junior Accountant",
  "Jefe de Ventas",
  "Jurist",
  "Junior Software Engineer",
  "Junior Designer",
  "Junior Software Developer",
  "Junior Associate",
  "Key Account Manager",
  "Kindergarten Teacher",
  "Konsulent",
  "KAM",
  "Key Account Executive",
  "Key Accounts Manager",
  "Konsult",
  "Kitchen Manager",
  "Key Account",
  "Key Holder",
  "Karyawan",
  "Kunderådgiver",
  "Kitchen Designer",
  "Koordinator",
  "Kontorassistent",
  "Kierownik",
  "Kundekonsulent",
  "Keyholder",
  "Key Account Specialist",
  "Knowledge Manager",
  "Lecturer",
  "Legal Assistant",
  "Lawyer",
  "Legal Secretary",
  "Librarian",
  "LPN",
  "Logistics Manager",
  "Loan Officer",
  "Lead Engineer",
  "Legal Counsel",
  "Logistics",
  "Logistics Coordinator",
  "Laboratory Technician",
  "Letter Carrier",
  "Law Clerk",
  "Lab Technician",
  "Lead Consultant",
  "Libero Professionista",
  "Lead Software Engineer",
  "Library Assistant",
  "Manager",
  "Managing Director",
  "Marketing Manager",
  "Marketing",
  "Mechanical Engineer",
  "Managing Partner",
  "Marketing Coordinator",
  "MD",
  "Marketing Director",
  "Mr",
  "Marketing Executive",
  "Medico",
  "Marketing Assistant",
  "Management Trainee",
  "Merchandiser",
  "Manufacturing Engineer",
  "Marketing Specialist",
  "Mechanic",
  "Medical Assistant",
  "Maintenance Manager",
  "Nurse",
  "Network Engineer",
  "Network Administrator",
  "None",
  "National Account Manager",
  "National Sales Manager",
  "Nurse Practitioner",
  "N A",
  "Ninguno",
  "NA",
  "Nurse Manager",
  "No",
  "Nursing",
  "Nutricionista",
  "Nanny",
  "Network Analyst",
  "Nil",
  "Network Technician",
  "Network Manager",
  "Network Specialist",
  "Owner",
  "Operations Manager",
  "Office Manager",
  "Officer",
  "Operator",
  "Office Administrator",
  "Office Assistant",
  "Operations",
  "Occupational Therapist",
  "Operations Supervisor",
  "Operations Director",
  "Operation Manager",
  "Operaio",
  "Operador",
  "Operations Analyst",
  "Operations Coordinator",
  "Office Coordinator",
  "Owner Operator",
  "Operations Specialist",
  "Outside Sales",
  "Project Manager",
  "Professor",
  "Partner",
  "President",
  "Project Engineer",
  "Product Manager",
  "Principal",
  "Program Manager",
  "Professora",
  "PhD Student",
  "Project Coordinator",
  "Production Manager",
  "Pharmacist",
  "Paralegal",
  "Process Engineer",
  "Profesor",
  "Programmer",
  "Physician",
  "Pilot",
  "Programmer Analyst",
  "Quality Manager",
  "Quality Engineer",
  "QA Engineer",
  "QA",
  "Quality Assurance",
  "Quantity Surveyor",
  "Quality Analyst",
  "Quality Assurance Manager",
  "Quadro",
  "QA Manager",
  "QA Analyst",
  "Quality Control",
  "Quality Assurance Analyst",
  "Quality Assurance Engineer",
  "Quality Assurance Specialist",
  "Quadro Direttivo",
  "QA Lead",
  "QC",
  "Quality Inspector",
  "Quality",
  "Realtor",
  "RN",
  "Registered Nurse",
  "Research Assistant",
  "Receptionist",
  "Researcher",
  "Regional Sales Manager",
  "Recruiter",
  "Research Associate",
  "Real Estate Agent",
  "Regional Manager",
  "Relationship Manager",
  "Recruitment Consultant",
  "Research Scientist",
  "Retraité",
  "Research Analyst",
  "Research Fellow",
  "Real Estate Broker",
  "Reporter",
  "Regional Director",
  "Student",
  "Software Engineer",
  "Sales Manager",
  "Sales",
  "Supervisor",
  "Software Developer",
  "Senior Consultant",
  "Sales Associate",
  "Senior Software Engineer",
  "Sales Representative",
  "Store Manager",
  "Senior Manager",
  "Secretary",
  "Senior Project Manager",
  "Sales Executive",
  "Senior Associate",
  "Senior Engineer",
  "System Engineer",
  "Systems Engineer",
  "Sales Consultant",
  "Teacher",
  "Team Leader",
  "Technician",
  "Territory Manager",
  "Team Lead",
  "Teaching Assistant",
  "Trainee",
  "Tecnico",
  "Technical Manager",
  "Technical Lead",
  "Test Engineer",
  "Trainer",
  "Technical Consultant",
  "Teller",
  "Team Manager",
  "Technical Support",
  "Tutor",
  "Technical Director",
  "Tech",
  "Technical Support Engineer",
  "Underwriter",
  "Unemployed",
  "Unit Manager",
  "Undergraduate Research Assistant",
  "UX Designer",
  "Uzman",
  "Unternehmensinhaber",
  "User Experience Designer",
  "Undergraduate Student",
  "Undergraduate Researcher",
  "Unit Secretary",
  "University Lecturer",
  "UI Designer",
  "Underwriting Assistant",
  "Uitvoerder",
  "Undergraduate",
  "Undersköterska",
  "UI Developer",
  "UI UX Designer",
  "University Professor",
  "Vice President",
  "VP",
  "Vendedor",
  "Volunteer",
  "Vendedora",
  "Ventas",
  "Verpleegkundige",
  "Visual Merchandiser",
  "Vice President of Operations",
  "Vice President of Sales",
  "VP Sales",
  "VP Operations",
  "VP Business Development",
  "Vigilante",
  "Vendas",
  "Vice President Business Development",
  "Vice President Sales",
  "Video Editor",
  "Vice President Operations",
  "Vice President Human Resources",
  "Web Developer",
  "Web Designer",
  "Warehouse Manager",
  "Writer",
  "Waitress",
  "Worker",
  "Warehouse Supervisor",
  "Welder",
  "Webmaster",
  "Waiter",
  "Warehouse",
  "Wissenschaftlicher Mitarbeiter",
  "Werkvoorbereider",
  "Warehouse Worker",
  "Warehouse Associate",
  "Web Application Developer",
  "Wealth Manager",
  "Work",
  "Wissenschaftliche Mitarbeiterin",
  "Webdesigner",
  "Xray Tech",
  "X-Ray Tech",
  "X-Ray Technologist",
  "Xray Technologist",
  "Yönetici",
  "Yoga Instructor",
  "Youth Worker",
  "Yoga Teacher",
  "Yönetmen",
  "Yok",
  "Yes",
  "Youth Pastor",
  "Yönetici Asistanı",
  "Yazılım Uzmanı",
  "Yetkili",
  "Yrd. Doç. Dr.",
  "Youth Counselor",
  "Y",
  "Yrd.Doç.Dr.",
  "YÖNETİCİ",
  "Youth Director",
  "Youth Care Worker",
  "Youth Minister",
  "Yacht Broker",
  "Zaakvoerder",
  "Zone Manager",
  "Zonal Manager",
  "Zonal Sales Manager",
  "Zumba Instructor",
  "Zonal Business Manager",
  "Zonal Head",
  "Zorgcoördinator",
  "Zorgcoordinator",
  "Zorgkundige",
  "Z",
  "Zootecnista",
  "Zelfstandig Ondernemer",
  "ZSM",
  "Zorgmanager",
  "Zone Merchandise Supervisor",
  "Zelfstandig",
  "Zelfstandige",
  "Ziekenverzorgende",
  "Zumba Fitness Instructor",
];
export const seniorities: string[] = [
  "Owner",
  "Founder",
  "C_suite",
  "Partner",
  "Vp",
  "Head",
  "Director",
  "Manager",
  "Senior",
  "Entry",
  "Intern",
];

export const emailStatusOptions: string[] = [
  "Verified",
  "Guessed",
  "Unavailable",
  "Bounced",
  "Pending Manual Fulfillment",
];

export const keywords = [
  { name: "Accounting", value: "5567ce1f7369643b78570000" },
  { name: "Agriculture", value: "55718f947369642142b84a12" },
  { name: "Airlines/Aviation", value: "5567e0bf7369641d115f0200" },
  { name: "Alternative Dispute Resolution", value: "5567e1a87369641f6d550100" },
  { name: "Alternative Medicine", value: "5567e27c7369642ade490000" },
  { name: "Animation", value: "5567e36f73696431a4970000" },
  { name: "Apparel & Fashion", value: "5567cd82736964540d0b0000" },
  { name: "Architecture & Planning", value: "5567cdb77369645401080000" },
  { name: "Arts & Crafts", value: "5567cd4d73696439d9030000" },
  { name: "Automotive", value: "5567cdf27369644cfd800000" },
  { name: "Aviation & Aerospace", value: "5567e0dd73696416d3c20100" },
  { name: "Banking", value: "5567ce237369644ee5490000" },
  { name: "Biotechnology", value: "5567d08e7369645dbc4b0000" },
  { name: "Broadcast Media", value: "5567e0f973696416d34e0200" },
  { name: "Building Materials", value: "5567e1a17369641ea9d30100" },
  { name: "Business Supplies & Equipment", value: "5567e0fa73696410e4c51200" },
  { name: "Capital Markets", value: "5567cdb773696439a9080000" },
  { name: "Chemicals", value: "5567e21e73696426a1030000" },
  { name: "Civic & Social Organization", value: "5567cdda7369644eed130000" },
  { name: "Civil Engineering", value: "5567e13a73696418756e0200" },
  { name: "Commercial Real Estate", value: "5567e1887369641d68d40100" },
  { name: "Computer & Network Security", value: "5567cd877369644cf94b0000" },
  { name: "Computer Games", value: "5567cd8b736964540d0f0000" },
  { name: "Computer Hardware", value: "5567e0d47369641233eb0600" },
  { name: "Computer Networking", value: "5567cdbe7369643b78360000" },
  { name: "Computer Software", value: "5567cd4e7369643b70010000" },
  { name: "Construction", value: "5567cd4773696439dd350000" },
  { name: "Consumer Electronics", value: "consumer electronics" },
  { name: "Consumer Goods", value: "5567e1947369641ead570000" },
  { name: "Consumer Services", value: "5567d1127261697f2b1d0000" },
  { name: "Cosmetics", value: "5567e1ae73696423dc040000" },
  { name: "Dairy", value: "5567e8a27369646ddb0b0000" },
  { name: "Defense & Space", value: "5567e1097369641b5f810500" },
  { name: "Design", value: "5567cdbc73696439d90b0000" },
  { name: "E-Learning", value: "5567e19c7369641c48e70100" },
  { name: "Education Management", value: "5567ce9e736964540d540000" },
  {
    name: "Electrical/Electronic Manufacturing",
    value: "5567cd4c73696439c9030000",
  },
  { name: "Entertainment", value: "5567cdd37369643b80510000" },
  { name: "Environmental Services", value: "5567ce5b736964540d280000" },
  { name: "Events Services", value: "5567cd8e7369645409450000" },
  { name: "Executive Office", value: "5567e09473696410dbf00700" },
  { name: "Facilities Services", value: "5567ce9c7369643bc9980000" },
  { name: "Farming", value: "5567cd4f7369644d2d010000" },
  { name: "Financial Services", value: "5567cdd67369643e64020000" },
  { name: "Fine Art", value: "5567e2097369642420150000" },
  { name: "Fishery", value: "5567f96c7369642a22080000" },
  { name: "Food & Beverages", value: "5567ce1e7369643b806a0000" },
  { name: "Food Production", value: "5567e1b3736964208b280000" },
  { name: "Fund-Raising", value: "5567d2ad7261697f2b1f0100" },
  { name: "Furniture", value: "5567cede73696440d0040000" },
  { name: "Gambling & Casinos", value: "5567e0cf7369641233e50600" },
  { name: "Glass, Ceramics & Concrete", value: "5567cd4f736964397e030000" },
  { name: "Government Administration", value: "5567cd527369643981050000" },
  { name: "Government Relations", value: "5567e29b736964256c370100" },
  { name: "Graphic Design", value: "5567cd4d73696439d9040000" },
  { name: "Health, Wellness & Fitness", value: "5567cddb7369644d250c0000" },
  { name: "Higher Education", value: "5567cd4c73696453e1300000" },
  { name: "Hospital & Health Care", value: "5567cdde73696439812c0000" },
  { name: "Hospitality", value: "5567ce9d7369643bc19c0000" },
  { name: "Human Resources", value: "5567e0e37369640e5ac10c00" },
  { name: "Import & Export", value: "5567ce9d7369645430c50000" },
  { name: "Individual & Family Services", value: "5567d02b7369645d8b140000" },
  { name: "Industrial Automation", value: "5567e1337369641ad2970000" },
  { name: "Information Services", value: "5567e0c97369640d2b3b1600" },
  {
    name: "Information Technology & Services",
    value: "5567cd4773696439b10b0000",
  },
  { name: "Insurance", value: "5567cdd973696453d93f0000" },
  { name: "International Affairs", value: "5567e3657369642f4ec90000" },
  {
    name: "International Trade & Development",
    value: "5567ce9c7369644eed680000",
  },
  { name: "Internet", value: "5567cd4d736964397e020000" },
  { name: "Investment Banking", value: "5567e1ab7369641f6d660100" },
  { name: "Investment Management", value: "5567e0bc7369641d11550200" },
  { name: "Judiciary", value: "55680a8273696407b61f0000" },
  { name: "Law Enforcement", value: "5567e0e073696408da441e00" },
  { name: "Law Practice", value: "5567ce1f7369644d391c0000" },
  { name: "Legal Services", value: "5567ce2d7369644d25250000" },
  { name: "Legislative Office", value: "5567e1797369641c48c10100" },
  { name: "Leisure, Travel & Tourism", value: "5567cdd87369643bc12f0000" },
  { name: "Libraries", value: "556808697369647bfd420000" },
  { name: "Logistics & Supply Chain", value: "5567cd4973696439b9010000" },
  { name: "Luxury Goods & Jewelry", value: "5567cda97369644cfd3e0000" },
  { name: "Machinery", value: "5567cd4973696439d53c0000" },
  { name: "Management Consulting", value: "5567cdd47369643dbf260000" },
  { name: "Maritime", value: "5567cd8273696439b1240000" },
  { name: "Market Research", value: "5567e1387369641ec75d0200" },
  { name: "Marketing & Advertising", value: "5567cd467369644d39040000" },
  {
    name: "Mechanical or Industrial Engineering",
    value: "5567ce2673696453d95c0000",
  },
  { name: "Media Production", value: "5567e0ea7369640d2ba31600" },
  { name: "Medical Devices", value: "5567e1b97369641ea9690200" },
  { name: "Medical Practice", value: "5567d0467369645dbc200000" },
  { name: "Mental Health Care", value: "5567ce2773696454308f0000" },
  { name: "Military", value: "5567e2c572616932bb3b0000" },
  { name: "Mining & Metals", value: "5567e3f3736964395d7a0000" },
  { name: "Motion Pictures & Film", value: "5567cdd7736964540d130000" },
  { name: "Museums & Institutions", value: "5567e15373696422aa0a0000" },
  { name: "Music", value: "5567cd4f736964540d050000" },
  { name: "Nanotechnology", value: "5567e7be736964110e210000" },
  { name: "Newspapers", value: "5567cd4a73696439a9010000" },
  {
    name: "Nonprofit Organization Management",
    value: "5567cd4773696454303a0000",
  },
  { name: "Oil & Energy", value: "5567cdd97369645624020000" },
  { name: "Online Media", value: "5567cdb373696439dd540000" },
  { name: "Outsourcing/Offshoring", value: "5567d04173696457ee520000" },
  { name: "Package/Freight Delivery", value: "5567e8bb7369641a658f0000" },
  { name: "Packaging & Containers", value: "5567e36973696431a4480000" },
  { name: "Paper & Forest Products", value: "5567e97f7369641e57730100" },
  { name: "Performing Arts", value: "5567e0af7369641ec7300000" },
  { name: "Pharmaceuticals", value: "5567e0eb73696410e4bd1200" },
  { name: "Philanthropy", value: "5567ce9673696453d99f0000" },
  { name: "Photography", value: "5567cd4f7369644cfd250000" },
  { name: "Plastics", value: "5567cdda7369644cf95d0000" },
  { name: "Political Organization", value: "5567e25f736964256cff0000" },
  { name: "Primary/Secondary Education", value: "5567cdd97369645430680000" },
  { name: "Printing", value: "5567cd4d7369644d513e0000" },
  {
    name: "Professional Training & Coaching",
    value: "5567cd49736964541d010000",
  },
  { name: "Program Development", value: "5567e2907369642433e60200" },
  { name: "Public Policy", value: "5567e28a7369642ae2500000" },
  {
    name: "Public Relations & Communications",
    value: "5567ce5973696453d9780000",
  },
  { name: "Public Safety", value: "5567cd4a7369643ba9010000" },
  { name: "Publishing", value: "5567ce5b73696439a17a0000" },
  { name: "Railroad Manufacture", value: "5567e14673696416d38c0300" },
  { name: "Ranching", value: "5567fd5a73696442b0f20000" },
  { name: "Real Estate", value: "5567cd477369645401010000" },
  {
    name: "Recreational Facilities & Services",
    value: "5567e134736964214f5e0000",
  },
  { name: "Religious Institutions", value: "5567e0f27369640e5aed0c00" },
  { name: "Renewables & Environment", value: "5567cd49736964540d020000" },
  { name: "Research", value: "5567e09f736964160ebb0100" },
  { name: "Restaurants", value: "5567e0e0736964198de70700" },
  { name: "Retail", value: "5567ced173696450cb580000" },
  { name: "Security & Investigations", value: "5567e19b7369641ead740000" },
  { name: "Semiconductors", value: "5567e0d87369640e5aa30c00" },
  { name: "Shipbuilding", value: "5568047d7369646d406c0000" },
  { name: "Sporting Goods", value: "5567e113736964198d5e0800" },
  { name: "Sports", value: "5567ce227369644eed290000" },
  { name: "Staffing & Recruiting", value: "5567e09973696410db020800" },
  { name: "Supermarkets", value: "5567e2a97369642a553d0000" },
  { name: "Telecommunications", value: "5567cd4c7369644d39080000" },
  { name: "Textiles", value: "5567e1327369641d91ce0300" },
  { name: "Think Tanks", value: "5567e1de7369642069ea0100" },
  { name: "Tobacco", value: "55680085736964551e070000" },
  { name: "Translation & Localization", value: "5567e1097369641d91230300" },
  {
    name: "Transportation/Trucking/Railroad",
    value: "5567cd4e7369644cf93b0000",
  },
  { name: "Utilities", value: "5567e2127369642420170000" },
  {
    name: "Venture Capital & Private Equity",
    value: "5567e1587369641c48370000",
  },
  { name: "Veterinary", value: "5567ce9673696439d5c10000" },
  { name: "Warehousing", value: "5567e127736964181e700200" },
  { name: "Wholesale", value: "5567d01e73696457ee100000" },
  { name: "Wine & Spirits", value: "5567cd4d7369643b78100000" },
  { name: "Wireless", value: "5567e3ca736964371b130000" },
  { name: "Writing & Editing", value: "5567cdd973696439a1370000" },
];
